/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.ChiTietPhieuNhap;
import dao.ChiTietPhieuNhapDAO;
import Model.SanPham;
import dao.SanPhamDAO;
import dao.PhieuNhapDAO;
import Model.PhieuNhap;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.toedter.calendar.JDateChooser;
import dao.NhanVienDAO;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Date;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.awt.Desktop;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Thanh PC
 */
public class PhieuNhapHang extends javax.swing.JFrame {
    private String phanQuyen;
        private String tenTaiKhoan;
    private DefaultTableModel PhieuNhap_model;
    private DefaultTableModel CTPN_model;
    private String chucNang;
    private JTextField tuKhoaField;
    private JDateChooser tuKhoaDate;
    /**
     * Creates new form HoaDonBanHang
     */
    
    
    public PhieuNhapHang(String phanQuyen, String maNV) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.HienThiComboboxSanPham();
        this.VoHieuHoaBtn(false);
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        long millis = System.currentTimeMillis();   
        java.sql.Date ngayHoaDon= new java.sql.Date(millis);
        NgayNhapField.setText(dateFormat.format(ngayHoaDon));
        this.getAllPhieuNhap();
        this.tenTaiKhoan = maNV;
        this.phanQuyen = phanQuyen;
         MaNhanVienField.setText(maNV);
        TenNhanVienField.setText(NhanVienDAO.getInstance().getById(maNV).getTenNhanVien());
        
        this.setTimKiemField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DanhSachPhieuNhap = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DanhSachCTPN = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        TriGiaValue = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ThemPNBtn = new javax.swing.JButton();
        HuyPNBtn = new javax.swing.JButton();
        InPNBtn = new javax.swing.JButton();
        ThoatBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        MaPhieuNhapLabel = new javax.swing.JLabel();
        MaPhieuNhapField = new javax.swing.JTextField();
        NgayNhapLabel = new javax.swing.JLabel();
        NgayNhapField = new javax.swing.JTextField();
        MaNhanVienLabel = new javax.swing.JLabel();
        MaNhanVienField = new javax.swing.JTextField();
        TenNhanVienLabel = new javax.swing.JLabel();
        TenNhanVienField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        TuKhoaLabel = new javax.swing.JLabel();
        TimKiemTheoLabel = new javax.swing.JLabel();
        TimKiemField = new javax.swing.JComboBox<>();
        TimKiemBtn = new javax.swing.JButton();
        TimKiemPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MaSanPhamLabel = new javax.swing.JLabel();
        MaSanPhamField = new javax.swing.JComboBox<>();
        TenSanPhamLabel = new javax.swing.JLabel();
        TenSanPhamField = new javax.swing.JTextField();
        SoLuongLabel = new javax.swing.JLabel();
        SoLuongField = new javax.swing.JTextField();
        DonGiaLabel = new javax.swing.JLabel();
        DonGiaField = new javax.swing.JTextField();
        ThemBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        AnhLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 215));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("PHIẾU NHẬP");

        DanhSachPhieuNhap.setBackground(new java.awt.Color(255, 255, 255));
        DanhSachPhieuNhap.setForeground(new java.awt.Color(0, 0, 0));
        DanhSachPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu nhập", "Mã nhân viên", "Ngày nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DanhSachPhieuNhap.setGridColor(new java.awt.Color(102, 102, 102));
        DanhSachPhieuNhap.setSelectionBackground(new java.awt.Color(153, 255, 153));
        DanhSachPhieuNhap.setSelectionForeground(new java.awt.Color(0, 0, 0));
        DanhSachPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DanhSachPhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DanhSachPhieuNhap);
        if (DanhSachPhieuNhap.getColumnModel().getColumnCount() > 0) {
            DanhSachPhieuNhap.getColumnModel().getColumn(0).setResizable(false);
            DanhSachPhieuNhap.getColumnModel().getColumn(1).setResizable(false);
            DanhSachPhieuNhap.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("CHI TIẾT PHIẾU NHẬP");

        DanhSachCTPN.setBackground(new java.awt.Color(255, 255, 255));
        DanhSachCTPN.setForeground(new java.awt.Color(0, 0, 0));
        DanhSachCTPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DanhSachCTPN.setGridColor(new java.awt.Color(102, 102, 102));
        DanhSachCTPN.setSelectionBackground(new java.awt.Color(153, 255, 153));
        DanhSachCTPN.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(DanhSachCTPN);
        if (DanhSachCTPN.getColumnModel().getColumnCount() > 0) {
            DanhSachCTPN.getColumnModel().getColumn(0).setResizable(false);
            DanhSachCTPN.getColumnModel().getColumn(1).setResizable(false);
            DanhSachCTPN.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 102));
        jLabel16.setText("TRỊ GIÁ:");

        TriGiaValue.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TriGiaValue.setForeground(new java.awt.Color(204, 0, 102));
        TriGiaValue.setToolTipText("");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        ThemPNBtn.setBackground(new java.awt.Color(0, 204, 102));
        ThemPNBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThemPNBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/add.png"))); // NOI18N
        ThemPNBtn.setText("Thêm");
        ThemPNBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThemPNBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemPNBtnActionPerformed(evt);
            }
        });
        jPanel5.add(ThemPNBtn);

        HuyPNBtn.setBackground(new java.awt.Color(0, 204, 102));
        HuyPNBtn.setForeground(new java.awt.Color(255, 255, 255));
        HuyPNBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/delete-button.png"))); // NOI18N
        HuyPNBtn.setText("Hủy phiếu nhập");
        HuyPNBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HuyPNBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyPNBtnActionPerformed(evt);
            }
        });
        jPanel5.add(HuyPNBtn);

        InPNBtn.setBackground(new java.awt.Color(0, 204, 102));
        InPNBtn.setForeground(new java.awt.Color(255, 255, 255));
        InPNBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/printer.png"))); // NOI18N
        InPNBtn.setText("In phiếu nhập");
        InPNBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InPNBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InPNBtnActionPerformed(evt);
            }
        });
        jPanel5.add(InPNBtn);

        ThoatBtn.setBackground(new java.awt.Color(0, 204, 102));
        ThoatBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThoatBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/exit.png"))); // NOI18N
        ThoatBtn.setText("Thoát");
        ThoatBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThoatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatBtnActionPerformed(evt);
            }
        });
        jPanel5.add(ThoatBtn);

        jPanel6.setBackground(new java.awt.Color(0, 204, 102));

        jLabel15.setBackground(new java.awt.Color(0, 204, 102));
        jLabel15.setFont(new java.awt.Font("DialogInput", 1, 28)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PHIẾU NHẬP HÀNG");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(422, 422, 422))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel15)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 153)));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));

        MaPhieuNhapLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        MaPhieuNhapLabel.setForeground(new java.awt.Color(0, 0, 0));
        MaPhieuNhapLabel.setText("Mã phiếu nhập");

        MaPhieuNhapField.setEditable(false);
        MaPhieuNhapField.setBackground(new java.awt.Color(255, 255, 255));
        MaPhieuNhapField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MaPhieuNhapField.setForeground(new java.awt.Color(0, 0, 0));
        MaPhieuNhapField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        MaPhieuNhapField.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        NgayNhapLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        NgayNhapLabel.setForeground(new java.awt.Color(0, 0, 0));
        NgayNhapLabel.setText("Ngày nhập");

        NgayNhapField.setEditable(false);
        NgayNhapField.setBackground(new java.awt.Color(255, 255, 255));
        NgayNhapField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NgayNhapField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NgayNhapField.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        NgayNhapField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NgayNhapFieldActionPerformed(evt);
            }
        });

        MaNhanVienLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        MaNhanVienLabel.setForeground(new java.awt.Color(0, 0, 0));
        MaNhanVienLabel.setText("Mã nhân viên");

        MaNhanVienField.setEditable(false);
        MaNhanVienField.setBackground(new java.awt.Color(255, 255, 255));
        MaNhanVienField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MaNhanVienField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        TenNhanVienLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        TenNhanVienLabel.setForeground(new java.awt.Color(0, 0, 0));
        TenNhanVienLabel.setText("Tên nhân viên");

        TenNhanVienField.setEditable(false);
        TenNhanVienField.setBackground(new java.awt.Color(255, 255, 255));
        TenNhanVienField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TenNhanVienField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(MaNhanVienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MaNhanVienField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(MaPhieuNhapField))
                    .addComponent(MaPhieuNhapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TenNhanVienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NgayNhapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(NgayNhapField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TenNhanVienField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaPhieuNhapLabel)
                    .addComponent(NgayNhapLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaPhieuNhapField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NgayNhapField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaNhanVienLabel)
                    .addComponent(TenNhanVienLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaNhanVienField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenNhanVienField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        TuKhoaLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        TuKhoaLabel.setForeground(new java.awt.Color(0, 0, 0));
        TuKhoaLabel.setText("Từ khóa");

        TimKiemTheoLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        TimKiemTheoLabel.setForeground(new java.awt.Color(0, 0, 0));
        TimKiemTheoLabel.setText("Tìm kiếm theo");

        TimKiemField.setBackground(new java.awt.Color(255, 255, 255));
        TimKiemField.setForeground(new java.awt.Color(0, 0, 0));
        TimKiemField.setBorder(null);
        TimKiemField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TimKiemFieldItemStateChanged(evt);
            }
        });

        TimKiemBtn.setBackground(new java.awt.Color(0, 204, 102));
        TimKiemBtn.setForeground(new java.awt.Color(255, 255, 255));
        TimKiemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/search.png"))); // NOI18N
        TimKiemBtn.setText("Tìm kiếm");
        TimKiemBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TimKiemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemBtnActionPerformed(evt);
            }
        });

        TimKiemPanel.setBackground(new java.awt.Color(255, 255, 255));
        TimKiemPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        TimKiemPanel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout TimKiemPanelLayout = new javax.swing.GroupLayout(TimKiemPanel);
        TimKiemPanel.setLayout(TimKiemPanelLayout);
        TimKiemPanelLayout.setHorizontalGroup(
            TimKiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        TimKiemPanelLayout.setVerticalGroup(
            TimKiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimKiemTheoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimKiemField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TuKhoaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimKiemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TimKiemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TuKhoaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TimKiemTheoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimKiemField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimKiemPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(TimKiemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(153, 153, 153)));

        MaSanPhamLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        MaSanPhamLabel.setForeground(new java.awt.Color(0, 0, 0));
        MaSanPhamLabel.setText("Mã sản phẩm");

        MaSanPhamField.setBackground(new java.awt.Color(255, 255, 255));
        MaSanPhamField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MaSanPhamField.setForeground(new java.awt.Color(0, 0, 0));
        MaSanPhamField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MaSanPhamFieldItemStateChanged(evt);
            }
        });

        TenSanPhamLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        TenSanPhamLabel.setForeground(new java.awt.Color(0, 0, 0));
        TenSanPhamLabel.setText("Tên sản phẩm");

        TenSanPhamField.setEditable(false);
        TenSanPhamField.setBackground(new java.awt.Color(255, 255, 255));
        TenSanPhamField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TenSanPhamField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        TenSanPhamField.setEnabled(false);

        SoLuongLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        SoLuongLabel.setForeground(new java.awt.Color(0, 0, 0));
        SoLuongLabel.setText("Số lượng");

        SoLuongField.setBackground(new java.awt.Color(255, 255, 255));
        SoLuongField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        SoLuongField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        DonGiaLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        DonGiaLabel.setForeground(new java.awt.Color(0, 0, 0));
        DonGiaLabel.setText("Đơn giá");

        DonGiaField.setBackground(new java.awt.Color(255, 255, 255));
        DonGiaField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DonGiaField.setForeground(new java.awt.Color(0, 0, 0));
        DonGiaField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        ThemBtn.setBackground(new java.awt.Color(0, 204, 102));
        ThemBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/add-to-basket.png"))); // NOI18N
        ThemBtn.setText("Thêm");
        ThemBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemBtnActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AnhLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AnhLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaSanPhamField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaSanPhamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SoLuongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SoLuongField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DonGiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DonGiaField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TenSanPhamField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(TenSanPhamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(ThemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaSanPhamLabel)
                    .addComponent(TenSanPhamLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaSanPhamField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenSanPhamField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(SoLuongLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SoLuongField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(DonGiaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DonGiaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ThemBtn)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TriGiaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(TriGiaValue))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14))
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void HienThiComboboxSanPham(){
        ArrayList<SanPham> sanPham = SanPhamDAO.getInstance().getAll();
        for (SanPham i : sanPham) {
            MaSanPhamField.addItem(i.getMaSanPham());
        }
    }
    private void VoHieuHoaBtn(boolean val) {       
        this.ThemPNBtn.setEnabled(!val);
        this.HuyPNBtn.setEnabled(!val);
        this.MaSanPhamField.setEnabled(val);
        this.SoLuongField.setEnabled(val);
        this.ThemBtn.setEnabled(val);       
    }
    
    private void TimKiemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemBtnActionPerformed
        // TODO add your handling code here:
        String timKiemTheo = (String) TimKiemField.getSelectedItem();
        ArrayList<PhieuNhap> phieuNhap = new ArrayList<>();
        if (!"".equals(tuKhoaField.getText()) || tuKhoaDate.getDate() != null) {
            if ("Mã phiếu nhập".equals(timKiemTheo)) {
                phieuNhap.add(PhieuNhapDAO.getInstance().getById(tuKhoaField.getText()));
            }else if ("Mã nhân viên".equals(timKiemTheo)) {
                phieuNhap = PhieuNhapDAO.getInstance().getByMaNhanVien(tuKhoaField.getText());
            }
            else if ("Ngày nhập".equals(timKiemTheo)) {
                phieuNhap = PhieuNhapDAO.getInstance().getByNgay(new Date(tuKhoaDate.getDate().getTime()));
            }else {
                JOptionPane.showMessageDialog(rootPane, "Không tìm thấy!");
            }
            this.hienThiPhieuNhap(phieuNhap);
        } else
            this.getAllPhieuNhap();
    }//GEN-LAST:event_TimKiemBtnActionPerformed

    private void DanhSachPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DanhSachPhieuNhapMouseClicked
        // TODO add your handling code here:
        int index = DanhSachPhieuNhap.getSelectedRow();
        ArrayList<ChiTietPhieuNhap> ctpn = ChiTietPhieuNhapDAO.getInstance().getById((String) PhieuNhap_model.getValueAt(index, 0));
        this.hienThiChiTietPhieuNhap(ctpn); 
        MaPhieuNhapField.setText((String) PhieuNhap_model.getValueAt(index, 0));
        MaNhanVienField.setText((String) PhieuNhap_model.getValueAt(index, 1));
        TenNhanVienField.setText(NhanVienDAO.getInstance().getById(MaNhanVienField.getText()).getTenNhanVien());
        NgayNhapField.setText((String) PhieuNhap_model.getValueAt(index, 2));
        TriGiaValue.setText(String.valueOf(PhieuNhapDAO.getInstance().getById((String) PhieuNhap_model.getValueAt(index, 0)).getTriGia()) + "   VND");
    }//GEN-LAST:event_DanhSachPhieuNhapMouseClicked

    private void HuyPNBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyPNBtnActionPerformed
        // TODO add your handling code here:
        int index = DanhSachPhieuNhap.getSelectedRow();
        PhieuNhapDAO.getInstance().delete((String) PhieuNhap_model.getValueAt(index, 0));  
        this.getAllPhieuNhap();
    }//GEN-LAST:event_HuyPNBtnActionPerformed

    private void ThemPNBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemPNBtnActionPerformed
        // TODO add your handling code here:
        VoHieuHoaBtn(true);
        if(PhieuNhap_model != null)
            PhieuNhap_model.setRowCount(0); 
        this.TriGiaValue.setText("0   VND");
        Date ngayNhap = null;
        try {
            ngayNhap= new Date(new SimpleDateFormat("dd/MM/yyyy").parse(NgayNhapField.getText()).getTime());
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        PhieuNhap pn = new PhieuNhap(PhieuNhapDAO.getInstance().getSoThuTu(), MaNhanVienField.getText(), ngayNhap, 0);
        PhieuNhapDAO.getInstance().insert(pn);
        String[] dataRow = {pn.getMaPhieuNhap(), pn.getMaNhanVien(), NgayNhapField.getText()};
        MaPhieuNhapField.setText(pn.getMaPhieuNhap());
        PhieuNhap_model.addRow(dataRow);
        if(CTPN_model != null)
            CTPN_model.setRowCount(0);
       
    }//GEN-LAST:event_ThemPNBtnActionPerformed

    private void MaSanPhamFieldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MaSanPhamFieldItemStateChanged
        // TODO add your handling code here:
        String name = SanPhamDAO.getInstance().getById(MaSanPhamField.getSelectedItem().toString()).getHinhAnh();
        AnhLabel.setIcon(new ImageIcon(new ImageIcon(name).getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH)));
        TenSanPhamField.setText(SanPhamDAO.getInstance().getById(MaSanPhamField.getSelectedItem().toString()).getTenSanPham());
    }//GEN-LAST:event_MaSanPhamFieldItemStateChanged

    private void ThemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemBtnActionPerformed
        // TODO add your handling code here:
        CTPN_model = (DefaultTableModel) DanhSachCTPN.getModel();        
        String tensanPham = SanPhamDAO.getInstance().getById(MaSanPhamField.getSelectedItem().toString()).getTenSanPham(); 
        if(!"".equals(SoLuongField.getText()) && !"".equals(DonGiaField.getText())){
            String[] dataRow = {MaSanPhamField.getSelectedItem().toString(),tensanPham, SoLuongField.getText(), DonGiaField.getText()};
            CTPN_model.addRow(dataRow);
            ChiTietPhieuNhap ctpn = new ChiTietPhieuNhap((String) PhieuNhap_model.getValueAt(0, 0), MaSanPhamField.getSelectedItem().toString(),Double.parseDouble(DonGiaField.getText()), Integer.parseInt(SoLuongField.getText()));
            ChiTietPhieuNhapDAO.getInstance().insert(ctpn);
            TriGiaValue.setText(DinhDangTienTe(PhieuNhapDAO.getInstance().getById(MaPhieuNhapField.getText()).getTriGia()) + "   VND");
        }
        
    }//GEN-LAST:event_ThemBtnActionPerformed

    private void TimKiemFieldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TimKiemFieldItemStateChanged
        // TODO add your handling code here:
        if("Ngày nhập".equals((String)TimKiemField.getSelectedItem())){ 
            tuKhoaDate = new JDateChooser();
            tuKhoaDate.setDateFormatString("dd/MM/yyyy");
            tuKhoaDate.setPreferredSize(new Dimension(TimKiemPanel.getWidth(), TimKiemPanel.getHeight()));
            TimKiemPanel.removeAll();
            TimKiemPanel.setLayout(new CardLayout());
            TimKiemPanel.add(tuKhoaDate);
            TimKiemPanel.validate();
            TimKiemPanel.repaint();
        }
        else{
            tuKhoaField = new JTextField();
            tuKhoaField.setPreferredSize(new Dimension(TimKiemPanel.getWidth(), TimKiemPanel.getHeight()));
            TimKiemPanel.removeAll();
            TimKiemPanel.setLayout(new CardLayout());
            TimKiemPanel.add(tuKhoaField);
            TimKiemPanel.validate();
            TimKiemPanel.repaint();
        }
    }//GEN-LAST:event_TimKiemFieldItemStateChanged

    private void InPNBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InPNBtnActionPerformed
        // TODO add your handling code here:
        if ("".equals(MaPhieuNhapField.getText())) {
            JOptionPane.showConfirmDialog(rootPane, "Vui lòng chọn phiếu nhập");
        } else {
            Document doc = new Document(PageSize.A5);
            String fileName = MaPhieuNhapField.getText();
            try {
                PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream("D:\\tptsport\\inventories\\" + fileName + ".pdf"));
                doc.open();
                File fileFontTieuDe = new File("src/resources/fonts/vuArialBold.ttf");
                BaseFont bfTieuDe = BaseFont.createFont(fileFontTieuDe.getAbsolutePath(), BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
                Font fontTieuDe1 = new Font(bfTieuDe, 15);
                Font fontTieuDe2 = new Font(bfTieuDe, 13);
                File fileFontNoiDung = new File("src/resources/fonts/vuArial.ttf");
                BaseFont bfNoiDung = BaseFont.createFont(fileFontNoiDung.getAbsolutePath(), BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
                Font fontNoiDung1 = new Font(bfNoiDung, 13);
                Font fontNoiDung2 = new Font(bfNoiDung, 12);

                Paragraph prgTenCuaHang = new Paragraph("TPT SPORT", fontTieuDe1);
                prgTenCuaHang.setAlignment(Element.ALIGN_CENTER);               
                doc.add(prgTenCuaHang);

                Paragraph prgDiaChi = new Paragraph("123 Đường số 4, Phường Linh Trung, Thành phố Thủ Đức, Thành phố Hồ Chí Minh, Việt Nam", fontNoiDung2);
                prgDiaChi.setAlignment(Element.ALIGN_CENTER);
                prgDiaChi.setAlignment(Paragraph.ALIGN_CENTER);
                prgDiaChi.setSpacingBefore(5);
                doc.add(prgDiaChi);

                Paragraph prgTieuDe = new Paragraph("PHIẾU NHẬP HÀNG", fontTieuDe1);
                prgTieuDe.setAlignment(Element.ALIGN_CENTER);
                prgTieuDe.setSpacingBefore(20);
                prgTieuDe.setSpacingAfter(20);
                doc.add(prgTieuDe);

                List listTTHD = new List(List.UNORDERED);
                listTTHD.add(new ListItem("Mã phiếu nhập: " + MaPhieuNhapField.getText(), fontNoiDung1));
                listTTHD.add(new ListItem("Tên nhân viên: " + TenNhanVienField.getText(), fontNoiDung1));
                listTTHD.add(new ListItem("Ngày nhập: " + NgayNhapField.getText(), fontNoiDung1));
                doc.add(listTTHD);
                
                PdfPTable tableSP = new PdfPTable(4);
                tableSP.setWidthPercentage(95);
                tableSP.setSpacingBefore(20);
                tableSP.setSpacingAfter(20);

                float[] tableSP_colWidths = {250, 100, 200, 200};
                tableSP.setWidths(tableSP_colWidths);
                PdfPCell cellTDSP = new PdfPCell(new Paragraph("Tên sản phẩm", fontTieuDe2));
                cellTDSP.setPaddingTop(5);
                cellTDSP.setPaddingBottom(5);
                cellTDSP.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellTDSP.setVerticalAlignment(Element.ALIGN_MIDDLE);
                
                tableSP.addCell(cellTDSP);

                PdfPCell cellTDSL = new PdfPCell(new Paragraph("SL", fontTieuDe2));
                cellTDSL.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellTDSL.setVerticalAlignment(Element.ALIGN_MIDDLE);
                cellTDSL.setPaddingTop(5);
                cellTDSL.setPaddingBottom(5);
                tableSP.addCell(cellTDSL);

                PdfPCell cellTDDG = new PdfPCell(new Paragraph("Đơn giá", fontTieuDe2));
                cellTDDG.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellTDDG.setVerticalAlignment(Element.ALIGN_MIDDLE);
                cellTDDG.setPaddingTop(5);
                cellTDDG.setPaddingBottom(5);
                tableSP.addCell(cellTDDG);

                PdfPCell cellTDTT = new PdfPCell(new Paragraph("Thành tiền", fontTieuDe2));
                cellTDTT.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellTDTT.setVerticalAlignment(Element.ALIGN_MIDDLE);
                cellTDTT.setPaddingTop(5);
                cellTDTT.setPaddingBottom(5);
                tableSP.addCell(cellTDTT);

                ArrayList<ChiTietPhieuNhap> ctpn = ChiTietPhieuNhapDAO.getInstance().getById(MaPhieuNhapField.getText());
                for (ChiTietPhieuNhap i : ctpn) {
                    String tenSP = SanPhamDAO.getInstance().getById(i.getMaSanPham()).getTenSanPham();
                    PdfPCell cellSP = new PdfPCell(new Paragraph(tenSP, fontNoiDung1));
                    cellSP.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cellSP.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    cellSP.setPaddingTop(5);
                    cellSP.setPaddingBottom(5);
                    tableSP.addCell(cellSP);

                    PdfPCell cellSL = new PdfPCell(new Paragraph(String.valueOf(i.getSoLuong()), fontNoiDung1));
                    cellSL.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cellSL.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    cellSL.setPaddingTop(5);
                    cellSL.setPaddingBottom(5);
                    tableSP.addCell(cellSL);


                    PdfPCell cellDG = new PdfPCell(new Paragraph(DinhDangTienTe(i.getSoLuong()), fontNoiDung1));
                    cellDG.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cellDG.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    cellTDSL.setPaddingTop(5);
                    cellTDSL.setPaddingBottom(5);
                    tableSP.addCell(cellDG);
                    
                    PdfPCell cellTT = new PdfPCell(new Paragraph(DinhDangTienTe(i.getSoLuong() * i.getDonGiaNhap()), fontNoiDung1));
                    cellTT.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cellTT.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    cellTDSL.setPaddingTop(5);
                    cellTDSL.setPaddingBottom(5);
                    tableSP.addCell(cellTT);
                    
                }
                doc.add(tableSP);
                
                PdfPTable tableTinhTien = new PdfPTable(2);
                tableTinhTien.setWidthPercentage(95);
                tableTinhTien.setSpacingAfter(20);
                
                float[]  tableTinhTien_colWidths = {450, 150};
                tableTinhTien.setWidths(tableTinhTien_colWidths);                

                PdfPCell cellTDTC = new PdfPCell(new Paragraph("Tổng tiền: " , fontTieuDe2));
                cellTDTC.setBorder(0);
                cellTDTC.setHorizontalAlignment(Element.ALIGN_RIGHT);
                cellTDTC.setVerticalAlignment(Element.ALIGN_MIDDLE);
                tableTinhTien.addCell(cellTDTC);
                PdfPCell cellTC = new PdfPCell(new Paragraph(DinhDangTienTe(PhieuNhapDAO.getInstance().getById(MaPhieuNhapField.getText()).getTriGia()), fontNoiDung1));
                cellTC.setBorder(0);
                cellTC.setHorizontalAlignment(Element.ALIGN_CENTER);
                cellTC.setVerticalAlignment(Element.ALIGN_MIDDLE);
                tableTinhTien.addCell(cellTC);
                doc.add(tableTinhTien);
                
                doc.close();
                writer.close();
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                File file = new File("D:\\tptsport\\inventories\\" + fileName + ".pdf");
                if(!Desktop.isDesktopSupported()){
                    System.out.println("not supported");
                    return;
                }
                Desktop desktop = Desktop.getDesktop();
                if(file.exists()){
                    desktop.open(file);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_InPNBtnActionPerformed

    private void NgayNhapFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NgayNhapFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NgayNhapFieldActionPerformed

    private void ThoatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatBtnActionPerformed
        // TODO add your handling code here:
        if("QL".equals(phanQuyen))
            new QuanLy_View(phanQuyen,tenTaiKhoan);
        else if("NVBH".equals(phanQuyen))
            new NhanVienBanHang_View(phanQuyen, tenTaiKhoan);
        else if("TK".equals(phanQuyen))
            new ThuKho_View(phanQuyen, tenTaiKhoan);
        this.dispose();
    }//GEN-LAST:event_ThoatBtnActionPerformed
    public String DinhDangTienTe(double SoTien) {
        Locale localeEN = new Locale("en", "EN");
        NumberFormat en = NumberFormat.getInstance(localeEN);

        String str = en.format(SoTien);
        return str;
    }
    /**
     * @param args the command line arguments
     */
    private void hienThiPhieuNhap(ArrayList<PhieuNhap> t) {
        PhieuNhap_model = (DefaultTableModel) DanhSachPhieuNhap.getModel();
        PhieuNhap_model.setRowCount(0);
        for (PhieuNhap i : t) {
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String ngayNhap = dateFormat.format(i.getNgayNhap());
            String[] dataRow = {i.getMaPhieuNhap(), i.getMaNhanVien(),ngayNhap};
            PhieuNhap_model.addRow(dataRow);
        }
    }
    
    private void getAllPhieuNhap() {
        ArrayList<PhieuNhap> phieuNhap = PhieuNhapDAO.getInstance().getAll();
        this.hienThiPhieuNhap(phieuNhap);
    }
    
    private void hienThiChiTietPhieuNhap(ArrayList<ChiTietPhieuNhap> t) {
        CTPN_model = (DefaultTableModel) DanhSachCTPN.getModel();
        double donGia;
        CTPN_model.setRowCount(0);
        for (ChiTietPhieuNhap i : t) {            
            String tensanPham = SanPhamDAO.getInstance().getById(i.getMaSanPham()).getTenSanPham();           
            String[] dataRow = {i.getMaSanPham(), tensanPham, String.valueOf(i.getSoLuong()), String.valueOf(i.getDonGiaNhap())};
            CTPN_model.addRow(dataRow);
        }        
    }
    private void setTimKiemField(){
        String [] tenCot ={"Mã phiếu nhập", "Mã nhân viên", "Ngày nhập"}; 
        for(int i = 0; i < tenCot.length; i++)
            TimKiemField.addItem(tenCot[i]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnhLabel;
    private javax.swing.JTable DanhSachCTPN;
    private javax.swing.JTable DanhSachPhieuNhap;
    private javax.swing.JTextField DonGiaField;
    private javax.swing.JLabel DonGiaLabel;
    private javax.swing.JButton HuyPNBtn;
    private javax.swing.JButton InPNBtn;
    private javax.swing.JTextField MaNhanVienField;
    private javax.swing.JLabel MaNhanVienLabel;
    private javax.swing.JTextField MaPhieuNhapField;
    private javax.swing.JLabel MaPhieuNhapLabel;
    private javax.swing.JComboBox<String> MaSanPhamField;
    private javax.swing.JLabel MaSanPhamLabel;
    private javax.swing.JTextField NgayNhapField;
    private javax.swing.JLabel NgayNhapLabel;
    private javax.swing.JTextField SoLuongField;
    private javax.swing.JLabel SoLuongLabel;
    private javax.swing.JTextField TenNhanVienField;
    private javax.swing.JLabel TenNhanVienLabel;
    private javax.swing.JTextField TenSanPhamField;
    private javax.swing.JLabel TenSanPhamLabel;
    private javax.swing.JButton ThemBtn;
    private javax.swing.JButton ThemPNBtn;
    private javax.swing.JButton ThoatBtn;
    private javax.swing.JButton TimKiemBtn;
    private javax.swing.JComboBox<String> TimKiemField;
    private javax.swing.JPanel TimKiemPanel;
    private javax.swing.JLabel TimKiemTheoLabel;
    private javax.swing.JLabel TriGiaValue;
    private javax.swing.JLabel TuKhoaLabel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
