/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.ChiTietHoaDon;
import Model.ChiTietPhieuNhap;
import dao.ChiTietPhieuNhapDAO;
import Model.SanPham;
import dao.SanPhamDAO;
import dao.PhieuNhapDAO;
import Model.PhieuNhap;
import com.toedter.calendar.JDateChooser;
import dao.NhanVienDAO;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanh PC
 */
public class PhieuNhapHang extends javax.swing.JFrame {

    private String phanQuyen;
    private String tenTaiKhoan;
    private DefaultTableModel PhieuNhap_model;
    private DefaultTableModel CTPN_model;
    private DefaultTableModel SP_model;
    private JTextField tuKhoaField;
    private JDateChooser tuKhoaDate;
    private ArrayList<ChiTietPhieuNhap> arr_CTPN;
    private Double triGia;

    /**
     * Creates new form HoaDonBanHang
     */
    public PhieuNhapHang(String phanQuyen, String maNV) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.VoHieuHoaBtn(false);
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        long millis = System.currentTimeMillis();
        java.sql.Date ngayHoaDon = new java.sql.Date(millis);
        NgayNhapField.setText(dateFormat.format(ngayHoaDon));
        this.getAllPhieuNhap();
        this.tenTaiKhoan = maNV;
        this.phanQuyen = phanQuyen;
        MaNhanVienField.setText(maNV);
        TenNhanVienField.setText(NhanVienDAO.getInstance().getById(maNV).getTenNhanVien());
        this.setTimKiemField();
        this.getAllSanPham();
        DanhSachPhieuNhap.setRowHeight(25);
        DanhSachCTPN.setRowHeight(25);
        DanhSachSanPham.setRowHeight(25);
        DanhSachCTPN.setEnabled(false);
        DanhSachSanPham.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DanhSachPhieuNhap = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DanhSachCTPN = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        TriGiaValue = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ThemPNBtn = new javax.swing.JButton();
        HuyPNBtn = new javax.swing.JButton();
        ThoatBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        MaPhieuNhapLabel = new javax.swing.JLabel();
        MaPhieuNhapField = new javax.swing.JTextField();
        NgayNhapLabel = new javax.swing.JLabel();
        NgayNhapField = new javax.swing.JTextField();
        MaNhanVienLabel = new javax.swing.JLabel();
        MaNhanVienField = new javax.swing.JTextField();
        TenNhanVienLabel = new javax.swing.JLabel();
        TenNhanVienField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        TuKhoaLabel = new javax.swing.JLabel();
        TimKiemPanel = new javax.swing.JPanel();
        TimKiemBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DanhSachSanPham = new javax.swing.JTable();
        TimKiemTheoLabel = new javax.swing.JLabel();
        TimKiemField = new javax.swing.JComboBox<>();
        DonGiaField = new javax.swing.JTextField();
        DonGiaLabel = new javax.swing.JLabel();
        SoLuongField = new javax.swing.JTextField();
        SoLuongLabel = new javax.swing.JLabel();
        TenSanPhamLabel = new javax.swing.JLabel();
        TenSanPhamField = new javax.swing.JTextField();
        MaSanPhamLabel = new javax.swing.JLabel();
        MaSanPhamField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        ThemBtn = new javax.swing.JButton();
        HuyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 215));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("PHIẾU NHẬP");

        DanhSachPhieuNhap.setBackground(new java.awt.Color(255, 255, 255));
        DanhSachPhieuNhap.setForeground(new java.awt.Color(0, 0, 0));
        DanhSachPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu nhập", "Mã nhân viên", "Ngày nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DanhSachPhieuNhap.setGridColor(new java.awt.Color(102, 102, 102));
        DanhSachPhieuNhap.setSelectionBackground(new java.awt.Color(153, 255, 153));
        DanhSachPhieuNhap.setSelectionForeground(new java.awt.Color(0, 0, 0));
        DanhSachPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DanhSachPhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DanhSachPhieuNhap);
        if (DanhSachPhieuNhap.getColumnModel().getColumnCount() > 0) {
            DanhSachPhieuNhap.getColumnModel().getColumn(0).setResizable(false);
            DanhSachPhieuNhap.getColumnModel().getColumn(1).setResizable(false);
            DanhSachPhieuNhap.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("CHI TIẾT PHIẾU NHẬP");

        DanhSachCTPN.setBackground(new java.awt.Color(255, 255, 255));
        DanhSachCTPN.setForeground(new java.awt.Color(0, 0, 0));
        DanhSachCTPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DanhSachCTPN.setGridColor(new java.awt.Color(102, 102, 102));
        DanhSachCTPN.setSelectionBackground(new java.awt.Color(153, 255, 153));
        DanhSachCTPN.setSelectionForeground(new java.awt.Color(0, 0, 0));
        DanhSachCTPN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DanhSachCTPNKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(DanhSachCTPN);
        if (DanhSachCTPN.getColumnModel().getColumnCount() > 0) {
            DanhSachCTPN.getColumnModel().getColumn(2).setResizable(false);
            DanhSachCTPN.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 102));
        jLabel16.setText("TRỊ GIÁ:");

        TriGiaValue.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TriGiaValue.setForeground(new java.awt.Color(204, 0, 102));
        TriGiaValue.setToolTipText("");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 50, 0));

        ThemPNBtn.setBackground(new java.awt.Color(0, 204, 102));
        ThemPNBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThemPNBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/add.png"))); // NOI18N
        ThemPNBtn.setText("Thêm");
        ThemPNBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThemPNBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemPNBtnActionPerformed(evt);
            }
        });
        jPanel5.add(ThemPNBtn);

        HuyPNBtn.setBackground(new java.awt.Color(0, 204, 102));
        HuyPNBtn.setForeground(new java.awt.Color(255, 255, 255));
        HuyPNBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/delete-button.png"))); // NOI18N
        HuyPNBtn.setText("Hủy phiếu");
        HuyPNBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HuyPNBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyPNBtnActionPerformed(evt);
            }
        });
        jPanel5.add(HuyPNBtn);

        ThoatBtn.setBackground(new java.awt.Color(0, 204, 102));
        ThoatBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThoatBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/exit.png"))); // NOI18N
        ThoatBtn.setText("Thoát");
        ThoatBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThoatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatBtnActionPerformed(evt);
            }
        });
        jPanel5.add(ThoatBtn);

        jPanel6.setBackground(new java.awt.Color(0, 204, 102));

        jLabel15.setBackground(new java.awt.Color(0, 204, 102));
        jLabel15.setFont(new java.awt.Font("DialogInput", 1, 28)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PHIẾU NHẬP HÀNG");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(469, 469, 469))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(16, 16, 16))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 153)));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));

        MaPhieuNhapLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        MaPhieuNhapLabel.setForeground(new java.awt.Color(0, 0, 0));
        MaPhieuNhapLabel.setText("Mã phiếu nhập");

        MaPhieuNhapField.setEditable(false);
        MaPhieuNhapField.setBackground(new java.awt.Color(255, 255, 255));
        MaPhieuNhapField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MaPhieuNhapField.setForeground(new java.awt.Color(0, 0, 0));
        MaPhieuNhapField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        MaPhieuNhapField.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        NgayNhapLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        NgayNhapLabel.setForeground(new java.awt.Color(0, 0, 0));
        NgayNhapLabel.setText("Ngày nhập");

        NgayNhapField.setEditable(false);
        NgayNhapField.setBackground(new java.awt.Color(255, 255, 255));
        NgayNhapField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NgayNhapField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NgayNhapField.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        MaNhanVienLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        MaNhanVienLabel.setForeground(new java.awt.Color(0, 0, 0));
        MaNhanVienLabel.setText("Mã nhân viên");

        MaNhanVienField.setEditable(false);
        MaNhanVienField.setBackground(new java.awt.Color(255, 255, 255));
        MaNhanVienField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MaNhanVienField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        TenNhanVienLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        TenNhanVienLabel.setForeground(new java.awt.Color(0, 0, 0));
        TenNhanVienLabel.setText("Tên nhân viên");

        TenNhanVienField.setEditable(false);
        TenNhanVienField.setBackground(new java.awt.Color(255, 255, 255));
        TenNhanVienField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TenNhanVienField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaPhieuNhapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaPhieuNhapField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaNhanVienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaNhanVienField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TenNhanVienField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenNhanVienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NgayNhapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NgayNhapField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaPhieuNhapLabel)
                    .addComponent(NgayNhapLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaPhieuNhapField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NgayNhapField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaNhanVienLabel)
                    .addComponent(TenNhanVienLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaNhanVienField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenNhanVienField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        TuKhoaLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        TuKhoaLabel.setForeground(new java.awt.Color(0, 0, 0));
        TuKhoaLabel.setText("Từ khóa");

        TimKiemPanel.setBackground(new java.awt.Color(255, 255, 255));
        TimKiemPanel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout TimKiemPanelLayout = new javax.swing.GroupLayout(TimKiemPanel);
        TimKiemPanel.setLayout(TimKiemPanelLayout);
        TimKiemPanelLayout.setHorizontalGroup(
            TimKiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TimKiemPanelLayout.setVerticalGroup(
            TimKiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        TimKiemBtn.setBackground(new java.awt.Color(0, 204, 102));
        TimKiemBtn.setForeground(new java.awt.Color(255, 255, 255));
        TimKiemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/search.png"))); // NOI18N
        TimKiemBtn.setText("Tìm kiếm");
        TimKiemBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TimKiemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TuKhoaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimKiemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TimKiemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(TuKhoaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimKiemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(TimKiemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(153, 153, 153)));

        DanhSachSanPham.setBackground(new java.awt.Color(255, 255, 255));
        DanhSachSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng còn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DanhSachSanPham.setGridColor(new java.awt.Color(102, 102, 102));
        DanhSachSanPham.setSelectionBackground(new java.awt.Color(153, 255, 153));
        DanhSachSanPham.setSelectionForeground(new java.awt.Color(0, 0, 0));
        DanhSachSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DanhSachSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(DanhSachSanPham);
        if (DanhSachSanPham.getColumnModel().getColumnCount() > 0) {
            DanhSachSanPham.getColumnModel().getColumn(0).setResizable(false);
            DanhSachSanPham.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        TimKiemTheoLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        TimKiemTheoLabel.setForeground(new java.awt.Color(0, 0, 0));
        TimKiemTheoLabel.setText("Tìm kiếm theo");

        TimKiemField.setBackground(new java.awt.Color(255, 255, 255));
        TimKiemField.setForeground(new java.awt.Color(0, 0, 0));
        TimKiemField.setBorder(null);
        TimKiemField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TimKiemFieldItemStateChanged(evt);
            }
        });

        DonGiaField.setBackground(new java.awt.Color(255, 255, 255));
        DonGiaField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DonGiaField.setForeground(new java.awt.Color(0, 0, 0));
        DonGiaField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        DonGiaLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        DonGiaLabel.setForeground(new java.awt.Color(0, 0, 0));
        DonGiaLabel.setText("Đơn giá");

        SoLuongField.setBackground(new java.awt.Color(255, 255, 255));
        SoLuongField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        SoLuongField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        SoLuongLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        SoLuongLabel.setForeground(new java.awt.Color(0, 0, 0));
        SoLuongLabel.setText("Số lượng");

        TenSanPhamLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        TenSanPhamLabel.setForeground(new java.awt.Color(0, 0, 0));
        TenSanPhamLabel.setText("Tên sản phẩm");

        TenSanPhamField.setBackground(new java.awt.Color(255, 255, 255));
        TenSanPhamField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TenSanPhamField.setForeground(new java.awt.Color(0, 0, 0));
        TenSanPhamField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        TenSanPhamField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TenSanPhamField.setEnabled(false);
        TenSanPhamField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TenSanPhamFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TenSanPhamFieldKeyReleased(evt);
            }
        });

        MaSanPhamLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        MaSanPhamLabel.setForeground(new java.awt.Color(0, 0, 0));
        MaSanPhamLabel.setText("Mã sản phẩm");

        MaSanPhamField.setBackground(new java.awt.Color(255, 255, 255));
        MaSanPhamField.setForeground(new java.awt.Color(0, 0, 0));
        MaSanPhamField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        MaSanPhamField.setCaretColor(new java.awt.Color(0, 0, 0));
        MaSanPhamField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        MaSanPhamField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        MaSanPhamField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MaSanPhamFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MaSanPhamFieldKeyReleased(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        ThemBtn.setBackground(new java.awt.Color(0, 204, 102));
        ThemBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/add-to-basket.png"))); // NOI18N
        ThemBtn.setText("Thêm");
        ThemBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemBtnActionPerformed(evt);
            }
        });
        jPanel8.add(ThemBtn);

        HuyBtn.setBackground(new java.awt.Color(0, 204, 102));
        HuyBtn.setForeground(new java.awt.Color(255, 255, 255));
        HuyBtn.setText("Hủy");
        HuyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HuyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyBtnActionPerformed(evt);
            }
        });
        jPanel8.add(HuyBtn);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TimKiemTheoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimKiemField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DonGiaField)
                    .addComponent(SoLuongField)
                    .addComponent(MaSanPhamField)
                    .addComponent(TenSanPhamField)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DonGiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TenSanPhamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaSanPhamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SoLuongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(TimKiemTheoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TimKiemField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(MaSanPhamLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MaSanPhamField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TenSanPhamLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TenSanPhamField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(SoLuongLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SoLuongField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DonGiaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DonGiaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TriGiaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TriGiaValue)
                        .addComponent(jLabel16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoHieuHoaBtn(boolean val) {
        this.HuyPNBtn.setVisible(!val);
        this.HuyBtn.setVisible(val);
        ThoatBtn.setVisible(!val);
        this.MaSanPhamField.setEnabled(val);
        this.TenSanPhamField.setEnabled(val);
        this.SoLuongField.setEnabled(val);
        this.DonGiaField.setEnabled(val);
        this.ThemBtn.setVisible(val);
    }

    private void TimKiemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemBtnActionPerformed
        // TODO add your handling code here:
        String timKiemTheo = (String) TimKiemField.getSelectedItem();
        ArrayList<PhieuNhap> phieuNhap = null;
        if (CTPN_model != null) {
            CTPN_model.setRowCount(0);
        }
        if (!"".equals(tuKhoaField.getText()) || tuKhoaDate != null) {
            if ("Mã phiếu nhập".equals(timKiemTheo)) {
                phieuNhap.add(PhieuNhapDAO.getInstance().getById(tuKhoaField.getText()));
            } else if ("Mã nhân viên".equals(timKiemTheo)) {
                phieuNhap = PhieuNhapDAO.getInstance().getByMaNhanVien(tuKhoaField.getText());
            } else if ("Ngày nhập".equals(timKiemTheo)) {
                System.out.println("Đang tìm kiếm");
                phieuNhap = PhieuNhapDAO.getInstance().getByNgay(new Date(tuKhoaDate.getDate().getTime()));

            }

            if (phieuNhap != null || !tuKhoaField.getText().contains("%")) {
                this.hienThiPhieuNhap(phieuNhap);
            } else {
                JOptionPane.showMessageDialog(null,
                                "Không tìm thấy!",
                                "",
                                JOptionPane.ERROR_MESSAGE);
            }
        } else
            this.getAllPhieuNhap();
    }//GEN-LAST:event_TimKiemBtnActionPerformed

    private void DanhSachPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DanhSachPhieuNhapMouseClicked
        // TODO add your handling code here:
        int index = DanhSachPhieuNhap.getSelectedRow();
        ArrayList<ChiTietPhieuNhap> ctpn = ChiTietPhieuNhapDAO.getInstance().getById((String) PhieuNhap_model.getValueAt(index, 0));
        this.hienThiChiTietPhieuNhap(ctpn);
        MaPhieuNhapField.setText((String) PhieuNhap_model.getValueAt(index, 0));
        MaNhanVienField.setText((String) PhieuNhap_model.getValueAt(index, 1));
        TenNhanVienField.setText(NhanVienDAO.getInstance().getById(MaNhanVienField.getText()).getTenNhanVien());
        NgayNhapField.setText(((String) PhieuNhap_model.getValueAt(index, 2)).trim());
        TriGiaValue.setText(String.valueOf(PhieuNhapDAO.getInstance().getById((String) PhieuNhap_model.getValueAt(index, 0)).getTriGia()) + "   VND");
    }//GEN-LAST:event_DanhSachPhieuNhapMouseClicked

    private void HuyPNBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyPNBtnActionPerformed
        // TODO add your handling code here:
        int index = DanhSachPhieuNhap.getSelectedRow();
        PhieuNhapDAO.getInstance().delete((String) PhieuNhap_model.getValueAt(index, 0));
        this.getAllPhieuNhap();
    }//GEN-LAST:event_HuyPNBtnActionPerformed

    private void ThemPNBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemPNBtnActionPerformed
        // TODO add your handling code here:

        triGia = 0.0;
        if ("Thêm".equals(ThemPNBtn.getText())) {
            DanhSachCTPN.setEnabled(true);
            DanhSachSanPham.setEnabled(true);
            VoHieuHoaBtn(true);
            ThemPNBtn.setText("Lưu");
            arr_CTPN = new ArrayList<>();
            if (PhieuNhap_model != null) {
                PhieuNhap_model.setRowCount(0);
            }
            if (CTPN_model != null) {
                CTPN_model.setRowCount(0);
            }
            this.TriGiaValue.setText("0   VND");
        } else if ("Lưu".equals(ThemPNBtn.getText())) {
            DanhSachCTPN.setEnabled(false);
            DanhSachSanPham.setEnabled(false);
            Date ngayNhap = null;
            try {
                ngayNhap = new Date(new SimpleDateFormat("dd/MM/yyyy").parse(NgayNhapField.getText()).getTime());
            } catch (ParseException ex) {
                Logger.getLogger(QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
            String stt = PhieuNhapDAO.getInstance().getSoThuTu();
            PhieuNhap pn = new PhieuNhap(stt, MaNhanVienField.getText(), ngayNhap, 0.0);
            PhieuNhapDAO.getInstance().insert(pn);
            for (ChiTietPhieuNhap i : arr_CTPN) {
                i.setMaPhieuNhap(pn.getMaPhieuNhap());
                ChiTietPhieuNhapDAO.getInstance().insert(i);
            }
            JOptionPane.showMessageDialog(null,
                    "Thêm phiếu nhập thành công!",
                    "",
                    JOptionPane.INFORMATION_MESSAGE);

            ThemPNBtn.setText("Thêm");
            VoHieuHoaBtn(false);
            this.getAllSanPham();
            this.getAllPhieuNhap();
            CTPN_model.setRowCount(0);

        }
    }//GEN-LAST:event_ThemPNBtnActionPerformed

    private void ThemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemBtnActionPerformed

        if (!"".equals(this.SoLuongField.getText()) || !"".equals(this.DonGiaField.getText()) || !"".equals(this.MaSanPhamField.getText()) || !"".equals(this.TenSanPhamField.getText())) {
            int soLuong = Integer.parseInt(SoLuongField.getText());
            try {
                soLuong = Integer.parseInt(SoLuongField.getText());
                if (soLuong <= 0) {
                    throw new ArithmeticException("");
                }
                String maSanPham = MaSanPhamField.getText();
                triGia = triGia + Double.parseDouble(DonGiaField.getText()) * Integer.parseInt(SoLuongField.getText());
                CTPN_model = (DefaultTableModel) DanhSachCTPN.getModel();
                String tensanPham = SanPhamDAO.getInstance().getById(maSanPham).getTenSanPham();
                ChiTietPhieuNhap ctpn = new ChiTietPhieuNhap("", maSanPham, Double.parseDouble(DonGiaField.getText()), soLuong);
                String[] dataRow = {maSanPham, tensanPham, SoLuongField.getText(), DonGiaField.getText()};
                CTPN_model.addRow(dataRow);
                if (!arr_CTPN.isEmpty()) {
                    for (ChiTietPhieuNhap i : arr_CTPN) {
                        int sl = i.getSoLuong();
                        if (i.getMaSanPham().equalsIgnoreCase(maSanPham)) {
                            i.setSoLuong(sl + Integer.parseInt(SoLuongField.getText()));
                        } else {
                            System.out.println(ctpn.getMaSanPham() + ctpn.getSoLuong());
                            arr_CTPN.add(ctpn);
                            break;
                        }
                    }
                } else {
                    arr_CTPN.add(ctpn);
                }
                TriGiaValue.setText(DinhDangTienTe(triGia));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        "Số lượng là chữ số lớn hơn 0",
                        "",
                        JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null,
                    "Vui lòng điền đầy đủ thông tin!",
                    "",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ThemBtnActionPerformed

    private void TimKiemFieldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TimKiemFieldItemStateChanged
        // TODO add your handling code here:
        if ("Ngày nhập".equals((String) TimKiemField.getSelectedItem())) {
            tuKhoaDate = new JDateChooser();
            tuKhoaDate.setDateFormatString("dd/MM/yyyy");
            tuKhoaDate.setPreferredSize(new Dimension(TimKiemPanel.getWidth(), TimKiemPanel.getHeight()));
            TimKiemPanel.removeAll();
            TimKiemPanel.setLayout(new CardLayout());
            TimKiemPanel.add(tuKhoaDate);
            TimKiemPanel.validate();
            TimKiemPanel.repaint();
        } else {
            tuKhoaField = new JTextField();
            tuKhoaField.setPreferredSize(new Dimension(TimKiemPanel.getWidth(), TimKiemPanel.getHeight()));
            TimKiemPanel.removeAll();
            TimKiemPanel.setLayout(new CardLayout());
            TimKiemPanel.add(tuKhoaField);
            TimKiemPanel.validate();
            TimKiemPanel.repaint();
        }
    }//GEN-LAST:event_TimKiemFieldItemStateChanged

    private void ThoatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatBtnActionPerformed
        // TODO add your handling code here:
        if ("QL".equals(phanQuyen)) {
            new QuanLy_View(phanQuyen, tenTaiKhoan);
        } else if ("NVBH".equals(phanQuyen)) {
            new NhanVienBanHang_View(phanQuyen, tenTaiKhoan);
        } else if ("TK".equals(phanQuyen)) {
            new ThuKho_View(phanQuyen, tenTaiKhoan);
        }
        this.dispose();
    }//GEN-LAST:event_ThoatBtnActionPerformed

    private void HuyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyBtnActionPerformed
        // TODO add your handling code here:
        VoHieuHoaBtn(false);
        this.getAllPhieuNhap();
        this.ThemPNBtn.setText("Thêm");
    }//GEN-LAST:event_HuyBtnActionPerformed

    private void DanhSachSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DanhSachSanPhamMouseClicked
        // TODO add your handling code here:
        int index = DanhSachSanPham.getSelectedRow();
        MaSanPhamField.setText((String) SP_model.getValueAt(index, 0));
        TenSanPhamField.setText((String) SP_model.getValueAt(index, 1));
    }//GEN-LAST:event_DanhSachSanPhamMouseClicked

    private void MaSanPhamFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MaSanPhamFieldKeyPressed
        // TODO add your handling code here:
        TenSanPhamField.setText("");
    }//GEN-LAST:event_MaSanPhamFieldKeyPressed

    private void TenSanPhamFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TenSanPhamFieldKeyPressed
        // TODO add your handling code here:
        MaSanPhamField.setText("");
    }//GEN-LAST:event_TenSanPhamFieldKeyPressed

    private void MaSanPhamFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MaSanPhamFieldKeyReleased
        // TODO add your handling code here:
        ArrayList<SanPham> sp = SanPhamDAO.getInstance().getByMaSanPham(MaSanPhamField.getText());
        this.hienThiDanhSachSanPham(sp);
    }//GEN-LAST:event_MaSanPhamFieldKeyReleased

    private void TenSanPhamFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TenSanPhamFieldKeyReleased
        // TODO add your handling code here:
        ArrayList<SanPham> sp = SanPhamDAO.getInstance().getByTen(TenSanPhamField.getText());
        this.hienThiDanhSachSanPham(sp);
    }//GEN-LAST:event_TenSanPhamFieldKeyReleased

    private void DanhSachCTPNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DanhSachCTPNKeyReleased
        // TODO add your handling code here:
        int index = DanhSachCTPN.getSelectedRow();
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            arr_CTPN.remove(index);
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int soSanPham = SanPhamDAO.getInstance().getById(CTPN_model.getValueAt(index, 0).toString()).getSoLuong();
            int soLuong = 0;
            try {
                soLuong = Integer.parseInt(CTPN_model.getValueAt(index, 2).toString());
                if (soLuong < 0) {
                    throw new ArithmeticException("");
                }                
                if(soLuong <= soSanPham){
                    if(soLuong == 0){
                        arr_CTPN.remove(index);
                    }
                    else{
                         ChiTietPhieuNhap t= new ChiTietPhieuNhap("", CTPN_model.getValueAt(index, 0).toString(), Double.parseDouble(DonGiaField.getText()), soLuong);
                    arr_CTPN.set(index, t);
                    }                  
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Số lượng sản phẩm còn lại: " + soSanPham);
                    SoLuongField.setFocusable(true);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        "Số lượng là chữ số lớn hơn 0",
                        "",
                        JOptionPane.ERROR_MESSAGE);
            }
            
        }
        if (arr_CTPN != null) {
            this.hienThiChiTietPhieuNhap(arr_CTPN);
        }
    }//GEN-LAST:event_DanhSachCTPNKeyReleased
    public String DinhDangTienTe(double SoTien) {
        Locale localeEN = new Locale("en", "EN");
        NumberFormat en = NumberFormat.getInstance(localeEN);

        String str = en.format(SoTien);
        return str;
    }

    /**
     * @param args the command line arguments
     */
    private void hienThiPhieuNhap(ArrayList<PhieuNhap> t) {
        PhieuNhap_model = (DefaultTableModel) DanhSachPhieuNhap.getModel();
        PhieuNhap_model.setRowCount(0);
        for (PhieuNhap i : t) {
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String ngayNhap = dateFormat.format(i.getNgayNhap());
            String[] dataRow = {i.getMaPhieuNhap(), i.getMaNhanVien(), ngayNhap};
            PhieuNhap_model.addRow(dataRow);
        }
    }

    private void getAllPhieuNhap() {
        ArrayList<PhieuNhap> phieuNhap = PhieuNhapDAO.getInstance().getAll();
        this.hienThiPhieuNhap(phieuNhap);
    }

    private void hienThiChiTietPhieuNhap(ArrayList<ChiTietPhieuNhap> t) {
        CTPN_model = (DefaultTableModel) DanhSachCTPN.getModel();
        CTPN_model.setRowCount(0);
        for (ChiTietPhieuNhap i : t) {
            String tensanPham = SanPhamDAO.getInstance().getById(i.getMaSanPham()).getTenSanPham();
            String[] dataRow = {i.getMaSanPham(), tensanPham, String.valueOf(i.getSoLuong()), String.valueOf(i.getDonGiaNhap())};
            CTPN_model.addRow(dataRow);
        }
    }

    private void hienThiDanhSachSanPham(ArrayList<SanPham> t) {
        SP_model = (DefaultTableModel) DanhSachSanPham.getModel();

        SP_model.setRowCount(0);
        for (SanPham i : t) {
            String[] dataRow = {i.getMaSanPham(), i.getTenSanPham(), String.valueOf(i.getSoLuong())};
            SP_model.addRow(dataRow);
        }
    }

    private void getAllSanPham() {
        ArrayList<SanPham> sanPham = SanPhamDAO.getInstance().getAll();
        this.hienThiDanhSachSanPham(sanPham);
    }

    private void setTimKiemField() {
        String[] tenCot = {"Mã phiếu nhập", "Mã nhân viên", "Ngày nhập"};
        for (int i = 0; i < tenCot.length; i++) {
            TimKiemField.addItem(tenCot[i]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DanhSachCTPN;
    private javax.swing.JTable DanhSachPhieuNhap;
    private javax.swing.JTable DanhSachSanPham;
    private javax.swing.JTextField DonGiaField;
    private javax.swing.JLabel DonGiaLabel;
    private javax.swing.JButton HuyBtn;
    private javax.swing.JButton HuyPNBtn;
    private javax.swing.JTextField MaNhanVienField;
    private javax.swing.JLabel MaNhanVienLabel;
    private javax.swing.JTextField MaPhieuNhapField;
    private javax.swing.JLabel MaPhieuNhapLabel;
    private javax.swing.JTextField MaSanPhamField;
    private javax.swing.JLabel MaSanPhamLabel;
    private javax.swing.JTextField NgayNhapField;
    private javax.swing.JLabel NgayNhapLabel;
    private javax.swing.JTextField SoLuongField;
    private javax.swing.JLabel SoLuongLabel;
    private javax.swing.JTextField TenNhanVienField;
    private javax.swing.JLabel TenNhanVienLabel;
    private javax.swing.JTextField TenSanPhamField;
    private javax.swing.JLabel TenSanPhamLabel;
    private javax.swing.JButton ThemBtn;
    private javax.swing.JButton ThemPNBtn;
    private javax.swing.JButton ThoatBtn;
    private javax.swing.JButton TimKiemBtn;
    private javax.swing.JComboBox<String> TimKiemField;
    private javax.swing.JPanel TimKiemPanel;
    private javax.swing.JLabel TimKiemTheoLabel;
    private javax.swing.JLabel TriGiaValue;
    private javax.swing.JLabel TuKhoaLabel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
