/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.NhanVien;
import dao.NhanVienDAO;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.Date;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.DateFormat;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JOptionPane;

/**
 *
 * @author Thanh PC
 */
public class QuanLyNhanVien extends javax.swing.JFrame {

    private String phanQuyen;
    private String tenTaiKhoan;
    private DefaultTableModel model;
    private String chucNang;
    private String regSDT;
    private String regEmail;

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien(String phanQuyen, String maQL) {
        initComponents();
        this.setVisible(true);
        this.setTitle("Quản lý nhân viên");
        this.setLocationRelativeTo(null);
        this.getAllNhanVien();
        this.VoHieuHoaBtn(false);
        NgaySinhField.setDateFormatString("dd/MM/yyyy");
        this.setTimKiemField();
        regSDT = "^(0|\\+84)(\\s|\\.)?((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\\d)(\\s|\\.)?(\\d{3})(\\s|\\.)?(\\d{3})$";
        regEmail = "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$";
        this.phanQuyen = phanQuyen;
        this.tenTaiKhoan = maQL;
        ChucVuField.setRenderer(new DefaultListCellRenderer() {
        @Override
        public void paint(Graphics g) {
            setForeground(Color.BLACK);
            setBackground(Color.WHITE);
            super.paint(g);
        }
        });
        DanhSachNhanVien.setRowHeight(25);                               
    }
    
    
    
    private void ThemNhanVien() throws ParseException {
        Date ngaySinh = new Date(NgaySinhField.getDate().getTime());
        Date ngayVaoLam = new Date(new SimpleDateFormat("dd/MM/yyyy").parse(NgayVaoLamField.getText()).getTime());
        String gioiTinh = "";
        if (jRadioButton1.isSelected()) {
            gioiTinh = jRadioButton1.getText();
        } else if (jRadioButton2.isSelected()) {
            gioiTinh = jRadioButton2.getText();
        }
       
        
        NhanVien nv = new NhanVien("", HoTenField.getText(), DiaChiField.getText(), SoDienThoaiField.getText(), EmailField.getText(), Long.parseLong(CCCDField.getText()), gioiTinh, ngaySinh, ngayVaoLam, ChucVuField.getSelectedItem().toString(), Double.parseDouble(LuongField.getText()));
        NhanVienDAO.getInstance().insert(nv);
        ResetValue();
        this.getAllNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GioiTinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DanhSachNhanVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        MaNhanVienLabel = new javax.swing.JLabel();
        MaNhanVienField = new javax.swing.JTextField();
        HoTenLabel = new javax.swing.JLabel();
        HoTenField = new javax.swing.JTextField();
        DiaChiLabel = new javax.swing.JLabel();
        DiaChiField = new javax.swing.JTextField();
        SoDienThoaiField = new javax.swing.JTextField();
        SoDienThoaiLabel = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        CCCDField = new javax.swing.JTextField();
        CCCDLabel = new javax.swing.JLabel();
        GioiTinhLabel = new javax.swing.JLabel();
        NgaySinhLabel = new javax.swing.JLabel();
        NgayVaoLamLabel = new javax.swing.JLabel();
        ChucVuField = new javax.swing.JComboBox<>();
        ChucVuLabel = new javax.swing.JLabel();
        NgaySinhField = new com.toedter.calendar.JDateChooser();
        NgayVaoLamField = new javax.swing.JTextField();
        LuongLabel = new javax.swing.JLabel();
        LuongField = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        TimKiemPanel = new javax.swing.JPanel();
        TimKiemField = new javax.swing.JComboBox<>();
        TimKiemLabel = new javax.swing.JLabel();
        TuKhoaField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TimKiemBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ThemBtn = new javax.swing.JButton();
        XoaBtn = new javax.swing.JButton();
        SuaBtn = new javax.swing.JButton();
        LuuBtn = new javax.swing.JButton();
        BoQuaBtn = new javax.swing.JButton();
        QuayLaiBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));

        DanhSachNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        DanhSachNhanVien.setForeground(new java.awt.Color(0, 0, 0));
        DanhSachNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ tên", "Địa chỉ", "Số điện thoại", "Email", "CCCD", "Giới tính", "Ngày sinh", "Ngày vào làm", "Chức vụ", "Lương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DanhSachNhanVien.setGridColor(new java.awt.Color(102, 102, 102));
        DanhSachNhanVien.setSelectionBackground(new java.awt.Color(153, 255, 153));
        DanhSachNhanVien.setSelectionForeground(new java.awt.Color(0, 0, 0));
        DanhSachNhanVien.getTableHeader().setReorderingAllowed(false);
        DanhSachNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DanhSachNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DanhSachNhanVien);
        if (DanhSachNhanVien.getColumnModel().getColumnCount() > 0) {
            DanhSachNhanVien.getColumnModel().getColumn(0).setResizable(false);
            DanhSachNhanVien.getColumnModel().getColumn(1).setResizable(false);
            DanhSachNhanVien.getColumnModel().getColumn(2).setResizable(false);
            DanhSachNhanVien.getColumnModel().getColumn(3).setResizable(false);
            DanhSachNhanVien.getColumnModel().getColumn(4).setResizable(false);
            DanhSachNhanVien.getColumnModel().getColumn(5).setResizable(false);
            DanhSachNhanVien.getColumnModel().getColumn(6).setResizable(false);
            DanhSachNhanVien.getColumnModel().getColumn(7).setResizable(false);
            DanhSachNhanVien.getColumnModel().getColumn(8).setResizable(false);
            DanhSachNhanVien.getColumnModel().getColumn(9).setResizable(false);
            DanhSachNhanVien.getColumnModel().getColumn(10).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QUẢN LÝ NHÂN VIÊN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(454, 454, 454))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 153)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        MaNhanVienLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        MaNhanVienLabel.setForeground(new java.awt.Color(0, 0, 0));
        MaNhanVienLabel.setText("Mã nhân viên");

        MaNhanVienField.setEditable(false);
        MaNhanVienField.setBackground(new java.awt.Color(255, 255, 255));
        MaNhanVienField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MaNhanVienField.setForeground(new java.awt.Color(0, 0, 0));
        MaNhanVienField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        MaNhanVienField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        MaNhanVienField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        MaNhanVienField.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        HoTenLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        HoTenLabel.setForeground(new java.awt.Color(0, 0, 0));
        HoTenLabel.setText("Họ tên");

        HoTenField.setBackground(new java.awt.Color(255, 255, 255));
        HoTenField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        HoTenField.setForeground(new java.awt.Color(0, 0, 0));
        HoTenField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        HoTenField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        HoTenField.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        DiaChiLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        DiaChiLabel.setForeground(new java.awt.Color(0, 0, 0));
        DiaChiLabel.setText("Địa chỉ");

        DiaChiField.setBackground(new java.awt.Color(255, 255, 255));
        DiaChiField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DiaChiField.setForeground(new java.awt.Color(0, 0, 0));
        DiaChiField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        DiaChiField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        SoDienThoaiField.setBackground(new java.awt.Color(255, 255, 255));
        SoDienThoaiField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        SoDienThoaiField.setForeground(new java.awt.Color(0, 0, 0));
        SoDienThoaiField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        SoDienThoaiField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        SoDienThoaiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoDienThoaiFieldActionPerformed(evt);
            }
        });

        SoDienThoaiLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        SoDienThoaiLabel.setForeground(new java.awt.Color(0, 0, 0));
        SoDienThoaiLabel.setText("Số điện thoại");

        EmailField.setBackground(new java.awt.Color(255, 255, 255));
        EmailField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        EmailField.setForeground(new java.awt.Color(0, 0, 0));
        EmailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        EmailField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        EmailField.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        EmailLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        EmailLabel.setText("Email");

        CCCDField.setBackground(new java.awt.Color(255, 255, 255));
        CCCDField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CCCDField.setForeground(new java.awt.Color(0, 0, 0));
        CCCDField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        CCCDField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        CCCDLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        CCCDLabel.setForeground(new java.awt.Color(0, 0, 0));
        CCCDLabel.setText("CCCD");

        GioiTinhLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        GioiTinhLabel.setForeground(new java.awt.Color(0, 0, 0));
        GioiTinhLabel.setText("Giới tính");

        NgaySinhLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        NgaySinhLabel.setForeground(new java.awt.Color(0, 0, 0));
        NgaySinhLabel.setText("Ngày sinh");

        NgayVaoLamLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        NgayVaoLamLabel.setForeground(new java.awt.Color(0, 0, 0));
        NgayVaoLamLabel.setText("Ngày vào làm");

        ChucVuField.setBackground(new java.awt.Color(255, 255, 255));
        ChucVuField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ChucVuField.setForeground(new java.awt.Color(0, 0, 0));
        ChucVuField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên bán hàng", "Nhân viên kho" }));

        ChucVuLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        ChucVuLabel.setForeground(new java.awt.Color(0, 0, 0));
        ChucVuLabel.setText("Chức vụ");

        NgaySinhField.setBackground(new java.awt.Color(255, 255, 255));
        NgaySinhField.setForeground(new java.awt.Color(0, 0, 0));
        NgaySinhField.setDateFormatString("dd,MM,yyyy");
        NgaySinhField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        NgayVaoLamField.setEditable(false);
        NgayVaoLamField.setBackground(new java.awt.Color(255, 255, 255));
        NgayVaoLamField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NgayVaoLamField.setForeground(new java.awt.Color(0, 0, 0));
        NgayVaoLamField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NgayVaoLamField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NgayVaoLamField.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        LuongLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        LuongLabel.setForeground(new java.awt.Color(0, 0, 0));
        LuongLabel.setText("Lương");

        LuongField.setEditable(false);
        LuongField.setBackground(new java.awt.Color(255, 255, 255));
        LuongField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LuongField.setForeground(new java.awt.Color(0, 0, 0));
        LuongField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        LuongField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        GioiTinh.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("Nam");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        GioiTinh.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setText("Nữ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaNhanVienField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiaChiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaNhanVienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NgayVaoLamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoTenField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoTenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SoDienThoaiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GioiTinhLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(NgayVaoLamField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(SoDienThoaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DiaChiField))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(LuongField)
                            .addComponent(LuongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NgaySinhField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCCDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCCDField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChucVuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChucVuField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NgaySinhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaNhanVienLabel)
                            .addComponent(HoTenLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GioiTinhLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NgaySinhLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MaNhanVienField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HoTenField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2))
                    .addComponent(NgaySinhField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoDienThoaiLabel)
                    .addComponent(EmailLabel)
                    .addComponent(CCCDLabel)
                    .addComponent(NgayVaoLamLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SoDienThoaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CCCDField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NgayVaoLamField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiaChiLabel)
                    .addComponent(ChucVuLabel)
                    .addComponent(LuongLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChucVuField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LuongField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DiaChiField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        TimKiemPanel.setBackground(new java.awt.Color(255, 255, 255));
        TimKiemPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(153, 153, 153)));

        TimKiemField.setBackground(new java.awt.Color(255, 255, 255));
        TimKiemField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        TimKiemLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        TimKiemLabel.setForeground(new java.awt.Color(0, 0, 0));
        TimKiemLabel.setText("Tìm kiếm theo");

        TuKhoaField.setBackground(new java.awt.Color(255, 255, 255));
        TuKhoaField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TuKhoaField.setForeground(new java.awt.Color(0, 0, 0));
        TuKhoaField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Từ khóa");

        TimKiemBtn.setBackground(new java.awt.Color(0, 204, 102));
        TimKiemBtn.setForeground(new java.awt.Color(255, 255, 255));
        TimKiemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/search.png"))); // NOI18N
        TimKiemBtn.setText("Tìm kiếm");
        TimKiemBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TimKiemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TimKiemPanelLayout = new javax.swing.GroupLayout(TimKiemPanel);
        TimKiemPanel.setLayout(TimKiemPanelLayout);
        TimKiemPanelLayout.setHorizontalGroup(
            TimKiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimKiemPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(TimKiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimKiemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimKiemField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TuKhoaField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimKiemPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TimKiemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        TimKiemPanelLayout.setVerticalGroup(
            TimKiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimKiemPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(TimKiemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimKiemField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TuKhoaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TimKiemBtn)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimKiemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TimKiemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 35, 0));

        ThemBtn.setBackground(new java.awt.Color(0, 204, 102));
        ThemBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/add.png"))); // NOI18N
        ThemBtn.setText("Thêm");
        ThemBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemBtnActionPerformed(evt);
            }
        });
        jPanel5.add(ThemBtn);

        XoaBtn.setBackground(new java.awt.Color(0, 204, 102));
        XoaBtn.setForeground(new java.awt.Color(255, 255, 255));
        XoaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/delete-button.png"))); // NOI18N
        XoaBtn.setText("Xóa");
        XoaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaBtnActionPerformed(evt);
            }
        });
        jPanel5.add(XoaBtn);

        SuaBtn.setBackground(new java.awt.Color(0, 204, 102));
        SuaBtn.setForeground(new java.awt.Color(255, 255, 255));
        SuaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/edit.png"))); // NOI18N
        SuaBtn.setText("Sửa");
        SuaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SuaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaBtnActionPerformed(evt);
            }
        });
        jPanel5.add(SuaBtn);

        LuuBtn.setBackground(new java.awt.Color(0, 204, 102));
        LuuBtn.setForeground(new java.awt.Color(255, 255, 255));
        LuuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/save.png"))); // NOI18N
        LuuBtn.setText("Lưu");
        LuuBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LuuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuuBtnActionPerformed(evt);
            }
        });
        jPanel5.add(LuuBtn);

        BoQuaBtn.setBackground(new java.awt.Color(0, 204, 102));
        BoQuaBtn.setForeground(new java.awt.Color(255, 255, 255));
        BoQuaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/cancel.png"))); // NOI18N
        BoQuaBtn.setText("Hủy");
        BoQuaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoQuaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoQuaBtnActionPerformed(evt);
            }
        });
        jPanel5.add(BoQuaBtn);

        QuayLaiBtn.setBackground(new java.awt.Color(0, 204, 102));
        QuayLaiBtn.setForeground(new java.awt.Color(255, 255, 255));
        QuayLaiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/exit.png"))); // NOI18N
        QuayLaiBtn.setText("Thoát");
        QuayLaiBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuayLaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuayLaiBtnActionPerformed(evt);
            }
        });
        jPanel5.add(QuayLaiBtn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoHieuHoaBtn(boolean val) {
        this.ThemBtn.setEnabled(!val);
        this.XoaBtn.setEnabled(!val);
        this.SuaBtn.setEnabled(!val);
        this.BoQuaBtn.setEnabled(val);
        this.LuuBtn.setEnabled(val);
        this.HoTenField.setEnabled(val);
        this.SoDienThoaiField.setEnabled(val);
        this.EmailField.setEnabled(val);
        this.DiaChiField.setEnabled(val);
        this.CCCDField.setEnabled(val);
        this.ChucVuField.setEnabled(val);
        
    }

    private void ResetValue() {
        MaNhanVienField.setText("");
        HoTenField.setText("");
        SoDienThoaiField.setText("");
        EmailField.setText("");
        CCCDField.setText("");
        NgaySinhField.setDate(null);
        DiaChiField.setText("");
        ChucVuField.setSelectedItem("");
        GioiTinh.clearSelection();
        LuongField.setText("0");
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        long millis = System.currentTimeMillis();   
        java.sql.Date ngayVaoLam = new java.sql.Date(millis);
        NgayVaoLamField.setText(dateFormat.format(ngayVaoLam));
    }

    private void QuayLaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuayLaiBtnActionPerformed
        new QuanLy_View(phanQuyen, tenTaiKhoan);
        this.dispose();
    }//GEN-LAST:event_QuayLaiBtnActionPerformed

    private void LuuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuuBtnActionPerformed
        // TODO add your handling code here:
        if(!SoDienThoaiField.getText().matches(regSDT)){
            JOptionPane.showMessageDialog(rootPane, "Định dạng số điện thoại không đúng");
        }
        else if(!EmailField.getText().matches(regEmail)){
            JOptionPane.showMessageDialog(rootPane, "Định dạng email không đúng");
        }
        else{
            if (!"".equals(HoTenField.getText())) {
            if ("Them".equals(this.chucNang))
                try {
                ThemNhanVien();
            } catch (ParseException ex) {
                Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            } else if ("Sua".equals(this.chucNang)) {
                Date ngaySinh = new Date(NgaySinhField.getDate().getTime());
                Date ngayVaoLam = null;
                try {
                    ngayVaoLam = new Date(new SimpleDateFormat("dd/MM/yyyy").parse(NgayVaoLamField.getText()).getTime());
                } catch (ParseException ex) {
                    Logger.getLogger(QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
                String gioiTinh = "";
                if (jRadioButton1.isSelected()) {
                    gioiTinh = jRadioButton1.getText();
                } else if (jRadioButton2.isSelected()) {
                    gioiTinh = jRadioButton2.getText();
                }
                NhanVien nv = new NhanVien(MaNhanVienField.getText(), HoTenField.getText(), DiaChiField.getText(), SoDienThoaiField.getText(), EmailField.getText(), Long.parseLong(CCCDField.getText()), gioiTinh, ngaySinh, ngayVaoLam, ChucVuField.getSelectedItem().toString(), Double.parseDouble(LuongField.getText()));
                NhanVienDAO.getInstance().update(nv);
            }
            this.VoHieuHoaBtn(false);
            this.getAllNhanVien();
            this.ResetValue();

        } else
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin!");
        
        }
        
    }//GEN-LAST:event_LuuBtnActionPerformed

    private void ThemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemBtnActionPerformed
        // TODO add your handling code here:
        this.ResetValue();
        VoHieuHoaBtn(true);
        this.HoTenField.requestFocus();
        this.chucNang = "Them";
    }//GEN-LAST:event_ThemBtnActionPerformed

    private void XoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaBtnActionPerformed
        // TODO add your handling code here:
        int index = DanhSachNhanVien.getSelectedRow();

        if (index == -1) {
            JOptionPane.showMessageDialog(rootPane, "Chọn dòng cần xóa");
        } else {
            if (NhanVienDAO.getInstance().delete((String) model.getValueAt(index, 0)) == 0) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi! Không thể xóa.");
            } else {
                this.ResetValue();
                this.getAllNhanVien();
            }
        }
    }//GEN-LAST:event_XoaBtnActionPerformed

    private void BoQuaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoQuaBtnActionPerformed
        // TODO add your handling code here:
        this.VoHieuHoaBtn(false);
        this.ResetValue();
    }//GEN-LAST:event_BoQuaBtnActionPerformed

    private void DanhSachNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DanhSachNhanVienMouseClicked
        // TODO add your handling code here:
        int index = DanhSachNhanVien.getSelectedRow();
        VoHieuHoaBtn(false);
        MaNhanVienField.setText((String) model.getValueAt(index, 0));
        HoTenField.setText((String) model.getValueAt(index, 1));
        DiaChiField.setText((String) model.getValueAt(index, 2));
        SoDienThoaiField.setText((String) model.getValueAt(index, 3));
        EmailField.setText((String) model.getValueAt(index, 4));
        CCCDField.setText((String) model.getValueAt(index, 5));
        if ("nam".equalsIgnoreCase((String) model.getValueAt(index, 6))) {
            jRadioButton1.setSelected(true);    
        } else if("nữ".equalsIgnoreCase((String) model.getValueAt(index, 6))) {
            jRadioButton2.setSelected(true);
        }

        try {
            java.util.Date date = new SimpleDateFormat("dd/MM/yyyy").parse((String) model.getValueAt(index, 7));
            NgaySinhField.setDate(date);
        } catch (ParseException ex) {
            System.out.println("Error: " + ex);
        }

        NgayVaoLamField.setText((String) model.getValueAt(index, 8));
        ChucVuField.setSelectedItem((String) model.getValueAt(index, 9));
        LuongField.setText((String) model.getValueAt(index, 10));
    }//GEN-LAST:event_DanhSachNhanVienMouseClicked

    private void SuaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaBtnActionPerformed
        // TODO add your handling code here:
        VoHieuHoaBtn(true);
        this.chucNang = "Sua";
    }//GEN-LAST:event_SuaBtnActionPerformed

    private void TimKiemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemBtnActionPerformed
        // TODO add your handling code here:
        String timKiemTheo = (String) TimKiemField.getSelectedItem();
        ArrayList<NhanVien> nhanVien = new ArrayList<>();
        if (!"".equals(TuKhoaField.getText())) {
            if ("Mã nhân viên".equals(timKiemTheo)) {
                nhanVien.add(NhanVienDAO.getInstance().getById(TuKhoaField.getText()));
            } else if ("Tên nhân viên".equals(timKiemTheo)) {
                nhanVien = NhanVienDAO.getInstance().getByTen(TuKhoaField.getText());
            }else if ("Giới tính".equals(timKiemTheo)) {
                nhanVien = NhanVienDAO.getInstance().getByGioiTinh(TuKhoaField.getText());
            }else if ("Chức vụ".equals(timKiemTheo)) {
                nhanVien = NhanVienDAO.getInstance().getByChucVu(TuKhoaField.getText());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Không tìm thấy!");
            }
            this.hienThi(nhanVien);
        } else
            this.getAllNhanVien();
    }//GEN-LAST:event_TimKiemBtnActionPerformed

    private void SoDienThoaiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoDienThoaiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoDienThoaiFieldActionPerformed

    private void hienThi(ArrayList<NhanVien> t) {
        model = (DefaultTableModel) DanhSachNhanVien.getModel();
        model.setRowCount(0);
        for (NhanVien i : t) {
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String ngayVaoLam = dateFormat.format(i.getNgayVaoLam());
            String ngaySinh = dateFormat.format(i.getNgaySinh());

            String[] dataRow = {i.getMaNhanVien(), i.getTenNhanVien(), i.getDiaChi(), i.getSoDienThoai(), i.getEmail(), String.valueOf(i.getCCCD()), i.getGioiTinh(), ngaySinh, ngayVaoLam, i.getChucVu(), String.valueOf(i.getLuong())};
            model.addRow(dataRow);
        }
    }

    private void getAllNhanVien() {
        ArrayList<NhanVien> nhanVien = NhanVienDAO.getInstance().getAll();
        this.hienThi(nhanVien);
    }
    
    private void setTimKiemField(){
        String [] tenCot ={"Mã nhân viên", "Tên nhân viên", "Giới tính", "Chức vụ"}; 
        for(int i = 0; i < tenCot.length; i++)
            TimKiemField.addItem(tenCot[i]);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoQuaBtn;
    private javax.swing.JTextField CCCDField;
    private javax.swing.JLabel CCCDLabel;
    private javax.swing.JComboBox<String> ChucVuField;
    private javax.swing.JLabel ChucVuLabel;
    private javax.swing.JTable DanhSachNhanVien;
    private javax.swing.JTextField DiaChiField;
    private javax.swing.JLabel DiaChiLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.ButtonGroup GioiTinh;
    private javax.swing.JLabel GioiTinhLabel;
    private javax.swing.JTextField HoTenField;
    private javax.swing.JLabel HoTenLabel;
    private javax.swing.JTextField LuongField;
    private javax.swing.JLabel LuongLabel;
    private javax.swing.JButton LuuBtn;
    private javax.swing.JTextField MaNhanVienField;
    private javax.swing.JLabel MaNhanVienLabel;
    private com.toedter.calendar.JDateChooser NgaySinhField;
    private javax.swing.JLabel NgaySinhLabel;
    private javax.swing.JTextField NgayVaoLamField;
    private javax.swing.JLabel NgayVaoLamLabel;
    private javax.swing.JButton QuayLaiBtn;
    private javax.swing.JTextField SoDienThoaiField;
    private javax.swing.JLabel SoDienThoaiLabel;
    private javax.swing.JButton SuaBtn;
    private javax.swing.JButton ThemBtn;
    private javax.swing.JButton TimKiemBtn;
    private javax.swing.JComboBox<String> TimKiemField;
    private javax.swing.JLabel TimKiemLabel;
    private javax.swing.JPanel TimKiemPanel;
    private javax.swing.JTextField TuKhoaField;
    private javax.swing.JButton XoaBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
