/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import Model.KhachHang;
import dao.KhachHangDAO;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanh PC
 */
public class QuanLyKhachHang extends javax.swing.JFrame {
    private String phanQuyen;
    private String tenTaiKhoan;
    private DefaultTableModel model;
    private String chucNang;
    private String regSDT;
    private String regEmail;
    
    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyKhachHang(String phanQuyen, String maNV) {
        initComponents();
        this.setVisible(true);
        this.setTitle("Quản lý khách hàng");
        this.setLocationRelativeTo(null);
        this.getAllKhachHang();
        this.VoHieuHoaBtn(false);
        NgaySinhField.setDateFormatString("dd/MM/yyyy");
        this.setTimKiemField();
        regSDT = "^(0|\\+84)(\\s|\\.)?((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\\d)(\\s|\\.)?(\\d{3})(\\s|\\.)?(\\d{3})$";
        regEmail = "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$";
        this.phanQuyen = phanQuyen;
        this.tenTaiKhoan = maNV;
    }
    private void VoHieuHoaBtn(boolean val) {
        this.ThemBtn.setEnabled(!val);
        this.XoaBtn.setEnabled(!val);
        this.SuaBtn.setEnabled(!val);
        this.BoQuaBtn.setEnabled(val);
        this.LuuBtn.setEnabled(val);
        this.HoTenField.setEnabled(val);
        this.SoDienThoaiField.setEnabled(val);
        this.EmailField.setEnabled(val);
        this.DiaChiField.setEnabled(val);
        this.NgaySinhField.setEnabled(val);
        this.CCCDField.setEnabled(val);    
    }

    private void ResetValue() {
        MaKhachHangField.setText("");
        HoTenField.setText("");
        SoDienThoaiField.setText("");
        EmailField.setText("");
        CCCDField.setText("");
        NgaySinhField.setDate(null);
        DiaChiField.setText("");
        DoanhSoField.setText("0");
        GioiTinh.clearSelection();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        long millis = System.currentTimeMillis();   
        java.sql.Date ngayDangKy = new java.sql.Date(millis);
        NgayDangKyField.setText(dateFormat.format(ngayDangKy));
    }                  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GioiTinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DanhSachKhachHang = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        MaNhanVienLabel = new javax.swing.JLabel();
        MaKhachHangField = new javax.swing.JTextField();
        HoTenLabel = new javax.swing.JLabel();
        HoTenField = new javax.swing.JTextField();
        DiaChiLabel = new javax.swing.JLabel();
        DiaChiField = new javax.swing.JTextField();
        SoDienThoaiField = new javax.swing.JTextField();
        SoDienThoaiLabel = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        CCCDField = new javax.swing.JTextField();
        CCCDLabel = new javax.swing.JLabel();
        GioiTinhLabel = new javax.swing.JLabel();
        NgaySinhLabel = new javax.swing.JLabel();
        NgayDangKyField = new javax.swing.JTextField();
        NgayVaoLamLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DoanhSoField = new javax.swing.JTextField();
        NgaySinhField = new com.toedter.calendar.JDateChooser();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        TimKiemPanel = new javax.swing.JPanel();
        TimKiemField = new javax.swing.JComboBox<>();
        TimKiemLabel = new javax.swing.JLabel();
        TuKhoaField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TimKiemBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ThemBtn = new javax.swing.JButton();
        XoaBtn = new javax.swing.JButton();
        SuaBtn = new javax.swing.JButton();
        LuuBtn = new javax.swing.JButton();
        BoQuaBtn = new javax.swing.JButton();
        QuayLaiBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 850));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));

        DanhSachKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        DanhSachKhachHang.setForeground(new java.awt.Color(0, 0, 0));
        DanhSachKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ tên", "Địa chỉ", "Số điện thoại", "Email", "CCCD", "Giới tính", "Ngày sinh", "Ngày đăng ký", "Doanh số"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DanhSachKhachHang.setGridColor(new java.awt.Color(153, 153, 153));
        DanhSachKhachHang.setSelectionBackground(new java.awt.Color(153, 204, 255));
        DanhSachKhachHang.getTableHeader().setReorderingAllowed(false);
        DanhSachKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DanhSachKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DanhSachKhachHang);
        if (DanhSachKhachHang.getColumnModel().getColumnCount() > 0) {
            DanhSachKhachHang.getColumnModel().getColumn(0).setResizable(false);
            DanhSachKhachHang.getColumnModel().getColumn(1).setResizable(false);
            DanhSachKhachHang.getColumnModel().getColumn(2).setResizable(false);
            DanhSachKhachHang.getColumnModel().getColumn(3).setResizable(false);
            DanhSachKhachHang.getColumnModel().getColumn(4).setResizable(false);
            DanhSachKhachHang.getColumnModel().getColumn(5).setResizable(false);
            DanhSachKhachHang.getColumnModel().getColumn(6).setResizable(false);
            DanhSachKhachHang.getColumnModel().getColumn(7).setResizable(false);
            DanhSachKhachHang.getColumnModel().getColumn(8).setResizable(false);
            DanhSachKhachHang.getColumnModel().getColumn(9).setResizable(false);
        }

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel4.setBackground(new java.awt.Color(0, 204, 102));
        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("QUẢN LÝ KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(15, 15, 15))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 153)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        MaNhanVienLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        MaNhanVienLabel.setForeground(new java.awt.Color(0, 0, 0));
        MaNhanVienLabel.setText("Mã khách hàng");

        MaKhachHangField.setEditable(false);
        MaKhachHangField.setBackground(new java.awt.Color(255, 255, 255));
        MaKhachHangField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MaKhachHangField.setForeground(new java.awt.Color(0, 0, 0));
        MaKhachHangField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        MaKhachHangField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        MaKhachHangField.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        HoTenLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        HoTenLabel.setForeground(new java.awt.Color(0, 0, 0));
        HoTenLabel.setText("Họ tên");

        HoTenField.setBackground(new java.awt.Color(255, 255, 255));
        HoTenField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        HoTenField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        HoTenField.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        DiaChiLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        DiaChiLabel.setForeground(new java.awt.Color(0, 0, 0));
        DiaChiLabel.setText("Địa chỉ");

        DiaChiField.setBackground(new java.awt.Color(255, 255, 255));
        DiaChiField.setForeground(new java.awt.Color(0, 0, 0));
        DiaChiField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        DiaChiField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        SoDienThoaiField.setBackground(new java.awt.Color(255, 255, 255));
        SoDienThoaiField.setForeground(new java.awt.Color(0, 0, 0));
        SoDienThoaiField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        SoDienThoaiField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        SoDienThoaiLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        SoDienThoaiLabel.setForeground(new java.awt.Color(0, 0, 0));
        SoDienThoaiLabel.setText("Số điện thoại");

        EmailField.setBackground(new java.awt.Color(255, 255, 255));
        EmailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        EmailField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        EmailLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        EmailLabel.setLabelFor(EmailLabel);
        EmailLabel.setText("Email");

        CCCDField.setBackground(new java.awt.Color(255, 255, 255));
        CCCDField.setForeground(new java.awt.Color(0, 0, 0));
        CCCDField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        CCCDField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        CCCDLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        CCCDLabel.setForeground(new java.awt.Color(0, 0, 0));
        CCCDLabel.setText("CCCD");

        GioiTinhLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        GioiTinhLabel.setForeground(new java.awt.Color(0, 0, 0));
        GioiTinhLabel.setText("Giới tính");

        NgaySinhLabel.setBackground(new java.awt.Color(0, 51, 153));
        NgaySinhLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        NgaySinhLabel.setForeground(new java.awt.Color(0, 0, 0));
        NgaySinhLabel.setText("Ngày sinh");

        NgayDangKyField.setEditable(false);
        NgayDangKyField.setBackground(new java.awt.Color(255, 255, 255));
        NgayDangKyField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NgayDangKyField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        NgayVaoLamLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        NgayVaoLamLabel.setForeground(new java.awt.Color(0, 0, 0));
        NgayVaoLamLabel.setText("Ngày đăng ký");

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Doanh số");

        DoanhSoField.setEditable(false);
        DoanhSoField.setBackground(new java.awt.Color(255, 255, 255));
        DoanhSoField.setForeground(new java.awt.Color(0, 0, 0));
        DoanhSoField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        DoanhSoField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        NgaySinhField.setBackground(new java.awt.Color(255, 255, 255));
        NgaySinhField.setForeground(new java.awt.Color(0, 0, 0));
        NgaySinhField.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        GioiTinh.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("Nam");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        GioiTinh.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setText("Nữ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SoDienThoaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaKhachHangField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCCDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCCDField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoDienThoaiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaNhanVienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(HoTenField)
                        .addComponent(EmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(HoTenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NgayVaoLamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NgayDangKyField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DoanhSoField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(DiaChiLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GioiTinhLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NgaySinhField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NgaySinhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(DiaChiField))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaNhanVienLabel)
                    .addComponent(HoTenLabel)
                    .addComponent(GioiTinhLabel)
                    .addComponent(NgaySinhLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NgaySinhField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MaKhachHangField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HoTenField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButton2)
                        .addComponent(jRadioButton1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(DiaChiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DiaChiField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(SoDienThoaiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SoDienThoaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(EmailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(CCCDLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(NgayVaoLamLabel))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(CCCDField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NgayDangKyField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DoanhSoField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        TimKiemPanel.setBackground(new java.awt.Color(255, 255, 255));
        TimKiemPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(153, 153, 153)));

        TimKiemField.setBackground(new java.awt.Color(255, 255, 255));

        TimKiemLabel.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        TimKiemLabel.setForeground(new java.awt.Color(0, 0, 0));
        TimKiemLabel.setText("Tìm kiếm theo");

        TuKhoaField.setBackground(new java.awt.Color(255, 255, 255));
        TuKhoaField.setForeground(new java.awt.Color(0, 0, 0));
        TuKhoaField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Từ khóa");

        TimKiemBtn.setBackground(new java.awt.Color(0, 204, 102));
        TimKiemBtn.setForeground(new java.awt.Color(255, 255, 255));
        TimKiemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/search.png"))); // NOI18N
        TimKiemBtn.setText("Tìm kiếm");
        TimKiemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TimKiemPanelLayout = new javax.swing.GroupLayout(TimKiemPanel);
        TimKiemPanel.setLayout(TimKiemPanelLayout);
        TimKiemPanelLayout.setHorizontalGroup(
            TimKiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimKiemPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(TimKiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TuKhoaField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimKiemField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimKiemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimKiemPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TimKiemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        TimKiemPanelLayout.setVerticalGroup(
            TimKiemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimKiemPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(TimKiemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimKiemField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TuKhoaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TimKiemBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimKiemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TimKiemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 35, 0));

        ThemBtn.setBackground(new java.awt.Color(0, 204, 102));
        ThemBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/add.png"))); // NOI18N
        ThemBtn.setText("Thêm");
        ThemBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemBtnActionPerformed(evt);
            }
        });
        jPanel5.add(ThemBtn);

        XoaBtn.setBackground(new java.awt.Color(0, 204, 102));
        XoaBtn.setForeground(new java.awt.Color(255, 255, 255));
        XoaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/delete-button.png"))); // NOI18N
        XoaBtn.setText("Xóa");
        XoaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaBtnActionPerformed(evt);
            }
        });
        jPanel5.add(XoaBtn);

        SuaBtn.setBackground(new java.awt.Color(0, 204, 102));
        SuaBtn.setForeground(new java.awt.Color(255, 255, 255));
        SuaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/edit.png"))); // NOI18N
        SuaBtn.setText("Sửa");
        SuaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SuaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaBtnActionPerformed(evt);
            }
        });
        jPanel5.add(SuaBtn);

        LuuBtn.setBackground(new java.awt.Color(0, 204, 102));
        LuuBtn.setForeground(new java.awt.Color(255, 255, 255));
        LuuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/save.png"))); // NOI18N
        LuuBtn.setText("Lưu");
        LuuBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LuuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuuBtnActionPerformed(evt);
            }
        });
        jPanel5.add(LuuBtn);

        BoQuaBtn.setBackground(new java.awt.Color(0, 204, 102));
        BoQuaBtn.setForeground(new java.awt.Color(255, 255, 255));
        BoQuaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/cancel.png"))); // NOI18N
        BoQuaBtn.setText("Hủy");
        BoQuaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoQuaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoQuaBtnActionPerformed(evt);
            }
        });
        jPanel5.add(BoQuaBtn);

        QuayLaiBtn.setBackground(new java.awt.Color(0, 204, 102));
        QuayLaiBtn.setForeground(new java.awt.Color(255, 255, 255));
        QuayLaiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/exit.png"))); // NOI18N
        QuayLaiBtn.setText("Thoát");
        QuayLaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuayLaiBtnActionPerformed(evt);
            }
        });
        jPanel5.add(QuayLaiBtn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(1043, 1043, 1043)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void ThemKhachHang() throws ParseException {
        Date ngaySinh = new Date(NgaySinhField.getDate().getTime());
        Date ngayDangKy = null;
        try {
            ngayDangKy = new Date(new SimpleDateFormat("dd/MM/yyyy").parse(NgayDangKyField.getText()).getTime());
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        String gioiTinh = "";
        if (jRadioButton1.isSelected()) {
            gioiTinh = jRadioButton1.getText();
        } else if (jRadioButton2.isSelected()) {
            gioiTinh = jRadioButton2.getText();
        }
        KhachHang kh = new KhachHang("", HoTenField.getText(), DiaChiField.getText(), SoDienThoaiField.getText(), EmailField.getText(), Long.parseLong(CCCDField.getText()), gioiTinh, ngaySinh, ngayDangKy, Double.parseDouble(DoanhSoField.getText()));
        KhachHangDAO.getInstance().insert(kh);
        ResetValue();
        this.getAllKhachHang();
    }
    
    private void DanhSachKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DanhSachKhachHangMouseClicked
        // TODO add your handling code here:
        int index = DanhSachKhachHang.getSelectedRow();
        VoHieuHoaBtn(false);
        MaKhachHangField.setText((String) model.getValueAt(index, 0));
        HoTenField.setText((String) model.getValueAt(index, 1));
        DiaChiField.setText((String) model.getValueAt(index, 2));
        SoDienThoaiField.setText((String) model.getValueAt(index, 3));
        EmailField.setText((String) model.getValueAt(index, 4));
        CCCDField.setText((String) model.getValueAt(index, 5));
        if ("nam".equalsIgnoreCase((String) model.getValueAt(index, 6))) {
            jRadioButton1.setSelected(true);    
        } else {
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(true);
        }

        try {
            java.util.Date date = new SimpleDateFormat("dd/MM/yyyy").parse((String) model.getValueAt(index, 7));
            NgaySinhField.setDate(date);
        } catch (ParseException ex) {
            System.out.println("Error: " + ex);
        }

        NgayDangKyField.setText((String) model.getValueAt(index, 8));
        DoanhSoField.setText((String) model.getValueAt(index, 9));

        
    }//GEN-LAST:event_DanhSachKhachHangMouseClicked

    private void BoQuaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoQuaBtnActionPerformed
        // TODO add your handling code here:
        this.VoHieuHoaBtn(false);
        this.ResetValue();
    }//GEN-LAST:event_BoQuaBtnActionPerformed

    private void XoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaBtnActionPerformed
        // TODO add your handling code here:
        int index = DanhSachKhachHang.getSelectedRow();

        if (index == -1) {
            JOptionPane.showMessageDialog(rootPane, "Chọn dòng cần xóa");
        } else {         
            if (KhachHangDAO.getInstance().delete((String) model.getValueAt(index, 0)) == 0) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi! Không thể xóa.");
            } else {
                this.ResetValue();
                this.getAllKhachHang();
            }
        }
    }//GEN-LAST:event_XoaBtnActionPerformed

    private void SuaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaBtnActionPerformed
        // TODO add your handling code here:
        VoHieuHoaBtn(true);
        this.chucNang = "Sua";
    }//GEN-LAST:event_SuaBtnActionPerformed

    private void ThemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemBtnActionPerformed
        // TODO add your handling code here:
        this.ResetValue();
        VoHieuHoaBtn(true);
        this.HoTenField.requestFocus();
        this.chucNang = "Them";

    }//GEN-LAST:event_ThemBtnActionPerformed

    private void LuuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuuBtnActionPerformed
        // TODO add your handling code here:\
        if(!SoDienThoaiField.getText().matches(regSDT)){
            JOptionPane.showMessageDialog(rootPane, "Định dạng số điện thoại không đúng");
        }
        else if(!EmailField.getText().matches(regEmail)){
            JOptionPane.showMessageDialog(rootPane, "Định dạng email không đúng");
        }
        else{
            if (!"".equals(HoTenField.getText())) {
            if ("Them".equals(this.chucNang))
                try {
                ThemKhachHang();
            } catch (ParseException ex) {
                Logger.getLogger(QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            } else if ("Sua".equals(this.chucNang)) {
                Date ngaySinh = new Date(NgaySinhField.getDate().getTime());
                Date ngayDangKy = null;
                try {
                    ngayDangKy = new Date(new SimpleDateFormat("dd/MM/yyyy").parse(NgayDangKyField.getText()).getTime());
                } catch (ParseException ex) {
                    Logger.getLogger(QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
                String gioiTinh = "";
                if (jRadioButton1.isSelected()) {
                    gioiTinh = jRadioButton1.getText();
                } else if (jRadioButton2.isSelected()) {
                    gioiTinh = jRadioButton2.getText();
                }
                KhachHang kh = new KhachHang(MaKhachHangField.getText(), HoTenField.getText(), DiaChiField.getText(), SoDienThoaiField.getText(), EmailField.getText(), Long.parseLong(CCCDField.getText()), gioiTinh, ngaySinh, ngayDangKy, Double.parseDouble(DoanhSoField.getText()));

                KhachHangDAO.getInstance().update(kh);
            }
            this.VoHieuHoaBtn(false);
            this.getAllKhachHang();
            this.ResetValue();

        } else
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin");
        }
        
    }                                      

                                      

                                        

    private void DanhSachMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:    
    }//GEN-LAST:event_LuuBtnActionPerformed

    private void TimKiemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemBtnActionPerformed
        // TODO add your handling code here:
        String timKiemTheo = (String) TimKiemField.getSelectedItem();
        ArrayList<KhachHang> khachHang = new ArrayList<>();
        if (!"".equals(TuKhoaField.getText())) {
            if ("Mã khách hàng".equals(timKiemTheo)) {
                khachHang.add(KhachHangDAO.getInstance().getById(TuKhoaField.getText()));
            } else if ("Tên khách hàng".equals(timKiemTheo)) {
                khachHang = KhachHangDAO.getInstance().getByTen(TuKhoaField.getText());
            }else if ("Giới tính".equals(timKiemTheo)) {
                khachHang = KhachHangDAO.getInstance().getByGioiTinh(TuKhoaField.getText());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Không tìm thấy!");
            }
            this.hienThi(khachHang);
        } else
            this.getAllKhachHang();
    }//GEN-LAST:event_TimKiemBtnActionPerformed

    private void QuayLaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuayLaiBtnActionPerformed
        // TODO add your handling code here:
        new NhanVienBanHang_View(phanQuyen, tenTaiKhoan);
        this.dispose();
    }//GEN-LAST:event_QuayLaiBtnActionPerformed
    
    private void hienThi(ArrayList<KhachHang> t) {
        model = (DefaultTableModel) DanhSachKhachHang.getModel();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        model.setRowCount(0);
        for (KhachHang i : t) {
            String ngayDangKy = dateFormat.format(i.getNgayDangKy());
            String ngaySinh = dateFormat.format(i.getNgaySinh());
            String[] dataRow = {i.getMaKhachHang(), i.getHoTen(), i.getDiaChi(), i.getSoDienThoai(), i.getEmail(), String.valueOf(i.getCCCD()), i.getGioiTinh(), ngaySinh, ngayDangKy, String.valueOf(i.getDoanhSo())};
            model.addRow(dataRow);
        }
    }

    private void getAllKhachHang() {
        ArrayList<KhachHang> khachHang = KhachHangDAO.getInstance().getAll();
        this.hienThi(khachHang);
    }
    
    private void setTimKiemField(){
        String [] tenCot ={"Mã khách hàng", "Tên khách hàng", "Giới tính"}; 
        for(int i = 0; i < tenCot.length; i++)
            TimKiemField.addItem(tenCot[i]);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoQuaBtn;
    private javax.swing.JTextField CCCDField;
    private javax.swing.JLabel CCCDLabel;
    private javax.swing.JTable DanhSachKhachHang;
    private javax.swing.JTextField DiaChiField;
    private javax.swing.JLabel DiaChiLabel;
    private javax.swing.JTextField DoanhSoField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.ButtonGroup GioiTinh;
    private javax.swing.JLabel GioiTinhLabel;
    private javax.swing.JTextField HoTenField;
    private javax.swing.JLabel HoTenLabel;
    private javax.swing.JButton LuuBtn;
    private javax.swing.JTextField MaKhachHangField;
    private javax.swing.JLabel MaNhanVienLabel;
    private javax.swing.JTextField NgayDangKyField;
    private com.toedter.calendar.JDateChooser NgaySinhField;
    private javax.swing.JLabel NgaySinhLabel;
    private javax.swing.JLabel NgayVaoLamLabel;
    private javax.swing.JButton QuayLaiBtn;
    private javax.swing.JTextField SoDienThoaiField;
    private javax.swing.JLabel SoDienThoaiLabel;
    private javax.swing.JButton SuaBtn;
    private javax.swing.JButton ThemBtn;
    private javax.swing.JButton TimKiemBtn;
    private javax.swing.JComboBox<String> TimKiemField;
    private javax.swing.JLabel TimKiemLabel;
    private javax.swing.JPanel TimKiemPanel;
    private javax.swing.JTextField TuKhoaField;
    private javax.swing.JButton XoaBtn;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
