CREATE TABLE CHITIETPHIEUNHAP(
    MAPHIEUNHAP CHAR(20),
    MASANPHAM CHAR(20),
    DONGIANHAP DOUBLE PRECISION,
    SOLUONG INT,

    CONSTRAINT PK_CTPN PRIMARY KEY(MAPHIEUNHAP,MASANPHAM) 
);
ALTER TABLE CHITIETPHIEUNHAP ADD CONSTRAINT FK01_CTPN FOREIGN KEY(MASANPHAM) REFERENCES SANPHAM(MASANPHAM);
ALTER TABLE CHITIETPHIEUNHAP ADD CONSTRAINT FK02_MAPHIEUNHAP FOREIGN KEY(MAPHIEUNHAP) REFERENCES PHIEUNHAP(MAPHIEUNHAP);