CREATE TABLE CHITIETHOADON(
    MAHOADON CHAR(20),
    MASANPHAM CHAR(20),
    MABAOHANH CHAR(20),
    SOLUONG INT,
    
    CONSTRAINT PK_CTHD PRIMARY KEY(MAHOADON,MASANPHAM)
);

ALTER TABLE CHITIETHOADON ADD CONSTRAINT FK01_CTHD FOREIGN KEY(MAHOADON) REFERENCES HOADON(MAHOADON);
ALTER TABLE CHITIETHOADON ADD CONSTRAINT FK02_CTHD FOREIGN KEY(MASANPHAM) REFERENCES SANPHAM(MASANPHAM);
ALTER TABLE CHITIETHOADON ADD CONSTRAINT FK03_CTHD FOREIGN KEY(MABAOHANH) REFERENCES PHIEUBAOHANH(MABAOHANH);