CREATE TABLE HOADON(
    MAHOADON CHAR(20) PRIMARY KEY,
    MAKHACHHANG CHAR(20),
    MANHANVIEN CHAR(20),
    MASUKIEN CHAR(20),
    NGAYHOADON DATE,
    TRIGIA DOUBLE PRECISION
);

ALTER TABLE HOADON ADD CONSTRAINT FK01_HOADON FOREIGN KEY(MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG);
ALTER TABLE HOADON ADD CONSTRAINT FK02_HOADON FOREIGN KEY(MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);
ALTER TABLE HOADON ADD CONSTRAINT FK03_HOADON FOREIGN KEY(MASUKIEN) REFERENCES SUKIEN(MASUKIEN);