CREATE TABLE KHACHHANG(
    MAKHACHHANG CHAR(20) PRIMARY KEY,
    HOTEN VARCHAR2(60),
    DIACHI VARCHAR2(200),
    SODIENTHOAI VARCHAR2(20),
    EMAIL VARCHAR2(50),
    CCCD LONG,
    GIOITINH CHAR(5),
    NGAYSINH DATE,
    NGAYDANGKI DATE,
    DOANHSO DOUBLE PRECISION,
    DIEMTICHLUY INT
);