CREATE TABLE NHANVIEN(
    MANHANVIEN CHAR(20) PRIMARY KEY,
    TENNHANVIEN VARCHAR2(50),
    TENDANGNHAP VARCHAR2(50),
    DIACHI VARCHAR2(200),
    SODIENTHOAI VARCHAR2(20),
    EMAIL VARCHAR2(100),
    CCCD LONG,
    GIOITINH CHAR(5),
    NGAYSINH DATE,
    NGAYVAOLAM DATE,
    CHUCVU VARCHAR2(40)
);
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN FOREIGN KEY(TENDANGNHAP) REFERENCES TAIKHOAN(TENDANGNHAP);