CREATE TABLE PHIEUNHAP(
    MAPHIEUNHAP CHAR(20) PRIMARY KEY,
    NGAYNHAP DATE,
    MANHANVIEN CHAR(20)
);
ALTER TABLE PHIEUNHAP ADD CONSTRAINT FK_PHIEUNHAP FOREIGN KEY(MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN);
