CREATE TABLE TAIKHOAN(
    TENDANGNHAP VARCHAR2(40) PRIMARY KEY,
    MATKHAU VARCHAR2(40),
    PHANQUYEN VARCHAR2(20),
    TRANGTHAI VARCHAR2(40)
)

INSERT TABLE TAIKHOAN('TPTSPORTNV01','123@123@','NHAN VIEN BAN HANG','Hoạt Động');
INSERT TABLE TAIKHOAN('TPTSPORTNV02','@123@123','NHAN VIEN BAN HANG','Hoạt Động');
INSERT TABLE TAIKHOAN('TPTSPORTNV03','123@@123','NHAN VIEN BAN HANG','Hoạt Động');
INSERT TABLE TAIKHOAN('TPTSPORTNV04','@123123@','NHAN VIEN BAN HANG','Hoạt Động');
INSERT TABLE TAIKHOAN('TPTSPORTNV05','@@123123','NHAN VIEN BAN HANG','Hoạt Động');
INSERT TABLE TAIKHOAN('TPTSPORTNV06','123123@@','NHAN VIEN BAN HANG','Hoạt Động');
INSERT TABLE TAIKHOAN('TPTSPORTNV07','321@321@','NHAN VIEN BAN HANG','Hoạt Động');
INSERT TABLE TAIKHOAN('TPTSPORTNV08','@321@321','NHAN VIEN BAN HANG','Hoạt Động');
INSERT TABLE TAIKHOAN('TPTSPORTNV09','321@@321','NHAN VIEN BAN HANG','Khóa');
INSERT TABLE TAIKHOAN('TPTSPORTNV10','@321321@','NHAN VIEN BAN HANG','Khóa');
INSERT TABLE TAIKHOAN('TPTSPORTNV11','@@321321','QUẢN LÝ','Hoạt Động');
INSERT TABLE TAIKHOAN('TPTSPORTNV12','321321@@','THỦ KHO','Hoạt Động');