INSERT INTO DANHMUC VALUES('DM01','GIÀY THỂ THAO');
INSERT INTO DANHMUC VALUES('DM02','QUẦN ÁO THỂ THAO');
INSERT INTO DANHMUC VALUES('DM03','VỢT CẦU LÔNG');
INSERT INTO DANHMUC VALUES('DM04','BALO-TÚI THỂ THAO');
INSERT INTO DANHMUC VALUES('DM05','PHỤ KIỆN');
INSERT INTO DANHMUC VALUES('DM06','BÓNG');